# Generated by Django 5.1.15 on 2026-09-17 09:18

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0012_microsofttenantconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('label', models.CharField(help_text='Human-readable partner/integration name', max_length=128)),
                ('key_id', models.CharField(db_index=True, help_text='Public key identifier, e.g. ak_live_7Qp2R9', max_length=64, unique=True)),
                ('secret_encrypted', models.TextField(help_text='Fernet-encrypted HMAC secret; never returned after issue time')),
                ('scopes', models.JSONField(default=list, help_text='Granted scope strings, subset of ALLOWED_SCOPES')),
                ('school_ids', models.JSONField(default=list, help_text='School IDs in scope; empty list = every school in the foundation')),
                ('ip_allowlist', models.JSONField(default=list, help_text='Optional CIDR/address list; empty = unrestricted (REQUIRED for payroll.write, PVA-013)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], db_index=True, default='ACTIVE', max_length=16)),
                ('rotated_from_id', models.BigIntegerField(blank=True, help_text='key_id (numeric pk) of the key this one supersedes', null=True)),
                ('read_only_at', models.DateTimeField(blank=True, help_text='PVA-012: superseded key becomes read-only (day 23 of overlap)', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='PVA-012: superseded key stops working (day 30 of overlap)', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partner_api_keys',
                'indexes': [models.Index(fields=['foundation_id', 'status'], name='partner_api_foundat_ec990d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartnerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(db_index=True, help_text='e.g. finance.payment.settled', max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending delivery'), ('DELIVERED', 'Delivered'), ('EXHAUSTED', 'Retries exhausted (pollable only)')], db_index=True, default='PENDING', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Failed delivery attempts so far')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'partner_events',
                'indexes': [models.Index(fields=['foundation_id', 'event_type'], name='partner_eve_foundat_621fdc_idx'), models.Index(fields=['foundation_id', 'status', 'next_attempt_at'], name='partner_eve_foundat_e374bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartnerWebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('url', models.URLField(help_text="Partner's HTTPS endpoint (https:// enforced)", max_length=500)),
                ('environment', models.CharField(default='LIVE', help_text='LIVE or TEST; one active endpoint per environment', max_length=16)),
                ('signing_secret_encrypted', models.TextField(help_text='Fernet-encrypted secret used to sign outgoing webhook deliveries')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'partner_webhook_endpoints',
                'indexes': [models.Index(fields=['foundation_id', 'environment', 'is_active'], name='partner_web_foundat_9eadcf_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('period', models.CharField(db_index=True, help_text='Payroll period YYYY-MM (e.g. 2026-08)', max_length=7)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved - awaiting partner acknowledgement'), ('ACKNOWLEDGED', 'Acknowledged by partner'), ('PAID', 'Paid (reserved for future payroll module)')], db_index=True, default='DRAFT', max_length=16)),
                ('gross_amount', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=18)),
                ('deduction_amount', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=18)),
                ('net_amount', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=18)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=64, null=True)),
                ('acknowledge_deadline', models.DateTimeField(blank=True, help_text='Approval + acknowledgement window; past this, ack is locked', null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, help_text='Partner key_id that acknowledged', max_length=64, null=True)),
                ('active_uniq_marker', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField())),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='identity.school')),
            ],
            options={
                'db_table': 'payroll_runs',
            },
        ),
        migrations.CreateModel(
            name='PayrollRunLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('staff_id', models.BigIntegerField(db_index=True, help_text='apps.identity.Staff ID')),
                ('staff_name', models.CharField(max_length=128)),
                ('gross_amount', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=18)),
                ('deduction_amount', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=18)),
                ('net_amount', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=18)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='partners.payrollrun')),
            ],
            options={
                'db_table': 'payroll_run_lines',
            },
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['foundation_id', 'school', 'status'], name='payroll_run_foundat_e111c3_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['foundation_id', 'period'], name='payroll_run_foundat_206b70_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'school', 'period', 'active_uniq_marker'), name='unique_active_payroll_run_per_school_period'),
        ),
        migrations.AddIndex(
            model_name='payrollrunline',
            index=models.Index(fields=['foundation_id', 'run'], name='payroll_run_foundat_78accf_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrunline',
            constraint=models.UniqueConstraint(fields=('run', 'staff_id'), name='unique_staff_per_payroll_run'),
        ),
    ]
