services:
  mysql:
    image: mysql:8.0
    container_name: educore_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: educore
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./deploy/mysql-init:/docker-entrypoint-initdb.d
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci

volumes:
  mysql_data:
