# Generated by Django 5.1.15 on 2026-09-15 07:35

import apps.core.fields
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0005_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='RptWalletActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField()),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('topups', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('purchases', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('commission', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('active_wallets', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(help_text='RPT-005: data freshness timestamp')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_activity_reports', to='identity.school')),
            ],
            options={
                'db_table': 'rpt_wallet_activity',
                'indexes': [models.Index(fields=['foundation_id', 'school_id', 'date'], name='rpt_wallet__foundat_8c1e28_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'school', 'date', 'currency'), name='unique_rpt_wallet_activity_per_school_day')],
            },
        ),
    ]
