# Generated by Django 5.1.15 on 2026-09-15 07:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_assessmentscore_version'),
        ('identity', '0005_staff'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RptDailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField()),
                ('present', models.PositiveIntegerField(default=0)),
                ('late', models.PositiveIntegerField(default=0)),
                ('sick', models.PositiveIntegerField(default=0)),
                ('permitted', models.PositiveIntegerField(default=0)),
                ('absent', models.PositiveIntegerField(default=0)),
                ('rate_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('computed_at', models.DateTimeField(help_text='RPT-005: data freshness timestamp')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_reports', to='academic.classgroup')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_attendance_reports', to='identity.school')),
            ],
            options={
                'db_table': 'rpt_daily_attendance',
                'indexes': [models.Index(fields=['foundation_id', 'school_id', 'date'], name='rpt_daily_a_foundat_afd7e8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'school', 'date', 'class_group'), name='unique_rpt_daily_attendance_per_school_class_day')],
            },
        ),
    ]
