# Generated by Django 5.1.15 on 2026-09-15 07:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_assessmentscore_version'),
        ('identity', '0005_staff'),
        ('reporting', '0002_rptdailyattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RptAcademicPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('avg_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('band_distribution', models.JSONField(default=dict, help_text='{descriptor: count}')),
                ('computed_at', models.DateTimeField(help_text='RPT-005: data freshness timestamp')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_reports', to='academic.classgroup')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_performance_reports', to='identity.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_reports', to='academic.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_reports', to='academic.term')),
            ],
            options={
                'db_table': 'rpt_academic_performance',
                'indexes': [models.Index(fields=['foundation_id', 'school_id', 'term_id'], name='rpt_academi_foundat_36152e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'school', 'term', 'class_group', 'subject'), name='unique_rpt_academic_performance_per_school_term_class_subject')],
            },
        ),
    ]
