# Generated by Django 5.1.15 on 2026-09-15 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_staff'),
        ('reporting', '0003_rptacademicperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RptActiveStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('month', models.DateField(help_text='Normalized to the 1st of the month')),
                ('active_count', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(help_text='RPT-005: data freshness timestamp')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_student_reports', to='identity.school')),
            ],
            options={
                'db_table': 'rpt_active_students',
                'indexes': [models.Index(fields=['foundation_id', 'school_id', 'month'], name='rpt_active__foundat_8964e1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'school', 'month'), name='unique_rpt_active_students_per_school_month')],
            },
        ),
    ]
