# Generated by Django 5.2.17 on 2026-09-15 10:42

import apps.core.fields
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_staff'),
        ('reporting', '0005_rptdailyfinance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RptArAging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('as_of', models.DateField()),
                ('bucket', models.CharField(help_text='CURRENT, 0_30, 31_60, 61_90, 90_PLUS', max_length=16)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('invoices_count', models.PositiveIntegerField(default=1)),
                ('computed_at', models.DateTimeField(help_text='RPT-005: data freshness timestamp')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_aging_reports', to='identity.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_aging_reports', to='identity.student')),
            ],
            options={
                'db_table': 'rpt_ar_aging',
                'indexes': [models.Index(fields=['foundation_id', 'school_id', 'as_of'], name='rpt_ar_agin_foundat_44aed0_idx'), models.Index(fields=['foundation_id', 'student_id', 'as_of'], name='rpt_ar_agin_foundat_2a8b67_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'school', 'student', 'as_of', 'bucket', 'currency'), name='unique_rpt_ar_aging_per_student_as_of_bucket')],
            },
        ),
    ]
