# Generated by Django 5.1.15 on 2026-09-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_remove_academicyear_unique_academic_year_name_per_school_and_more'),
        ('identity', '0005_staff'),
        ('reporting', '0006_rpt_ar_aging'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rptacademicperformance',
            name='unique_rpt_academic_performance_per_school_term_class_subject',
        ),
        migrations.RemoveConstraint(
            model_name='rptactivestudent',
            name='unique_rpt_active_students_per_school_month',
        ),
        migrations.RemoveConstraint(
            model_name='rptaraging',
            name='unique_rpt_ar_aging_per_student_as_of_bucket',
        ),
        migrations.RemoveConstraint(
            model_name='rptdailyattendance',
            name='unique_rpt_daily_attendance_per_school_class_day',
        ),
        migrations.RemoveConstraint(
            model_name='rptdailyfinance',
            name='unique_rpt_daily_finance_per_school_day',
        ),
        migrations.RemoveConstraint(
            model_name='rptwalletactivity',
            name='unique_rpt_wallet_activity_per_school_day',
        ),
        migrations.AddField(
            model_name='rptacademicperformance',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='rptactivestudent',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='rptaraging',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='rptdailyattendance',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='rptdailyfinance',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='rptwalletactivity',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddConstraint(
            model_name='rptacademicperformance',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'school', 'term', 'class_group', 'subject', 'active_uniq_marker'), name='unique_rpt_academic_performance_per_school_term_class_subject'),
        ),
        migrations.AddConstraint(
            model_name='rptactivestudent',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'school', 'month', 'active_uniq_marker'), name='unique_rpt_active_students_per_school_month'),
        ),
        migrations.AddConstraint(
            model_name='rptaraging',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'school', 'student', 'as_of', 'bucket', 'currency', 'active_uniq_marker'), name='unique_rpt_ar_aging_per_student_as_of_bucket'),
        ),
        migrations.AddConstraint(
            model_name='rptdailyattendance',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'school', 'date', 'class_group', 'active_uniq_marker'), name='unique_rpt_daily_attendance_per_school_class_day'),
        ),
        migrations.AddConstraint(
            model_name='rptdailyfinance',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'school', 'date', 'currency', 'active_uniq_marker'), name='unique_rpt_daily_finance_per_school_day'),
        ),
        migrations.AddConstraint(
            model_name='rptwalletactivity',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'school', 'date', 'currency', 'active_uniq_marker'), name='unique_rpt_wallet_activity_per_school_day'),
        ),
    ]
