# Generated by Django 5.1.15 on 2026-09-19 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0018_role_choice_labels_indonesian'),
        ('reporting', '0007_remove_rptacademicperformance_unique_rpt_academic_performance_per_school_term_class_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RptActiveStudentRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('month', models.DateField(help_text='Normalized to the 1st of the month')),
                ('student_ids', models.JSONField(default=list, help_text='Ids of the students counted, in ascending order')),
                ('captured_at', models.DateTimeField(help_text='When the roster was taken (same instant as the count)')),
                ('active_uniq_marker', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField())),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_student_rosters', to='identity.school')),
            ],
            options={
                'db_table': 'rpt_active_student_rosters',
                'indexes': [models.Index(fields=['foundation_id', 'school_id', 'month'], name='rpt_active__foundat_bc5fc3_idx')],
                'constraints': [models.UniqueConstraint(fields=('foundation_id', 'school', 'month', 'active_uniq_marker'), name='unique_rpt_active_student_roster_per_school_month')],
            },
        ),
    ]
