# Generated by Django 5.1.15 on 2026-09-19 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0019_user_activity_day'),
        ('reporting', '0008_rptactivestudentroster'),
    ]

    operations = [
        migrations.CreateModel(
            name='RptParentWeeklyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('week_start', models.DateField(help_text='Monday of the week (Asia/Jakarta calendar)')),
                ('active_parents', models.PositiveIntegerField(default=0)),
                ('enrolled_students', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(help_text='RPT-005: data freshness timestamp')),
                ('active_uniq_marker', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField())),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_weekly_activity_reports', to='identity.school')),
            ],
            options={
                'db_table': 'rpt_parent_weekly_activity',
                'indexes': [models.Index(fields=['foundation_id', 'school_id', 'week_start'], name='rpt_parent__foundat_a95ca5_idx')],
                'constraints': [models.UniqueConstraint(fields=('foundation_id', 'school', 'week_start', 'active_uniq_marker'), name='unique_rpt_parent_weekly_activity_per_school_week')],
            },
        ),
    ]
