# Generated by Django 5.1.15 on 2026-09-19 11:51

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0019_entitlement_history_module_price'),
        ('reporting', '0008_rptactivestudentroster'),
    ]

    operations = [
        migrations.CreateModel(
            name='RptSubscriptionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('month', models.DateField(help_text='Normalized to the 1st of the month')),
                ('module_key', models.CharField(max_length=32)),
                ('plan_tier', models.CharField(help_text="The foundation's tier when the row was computed", max_length=32)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('active_count', models.PositiveIntegerField(help_text="The month's `RptActiveStudent` count")),
                ('unit_price', apps.core.fields.MoneyField(decimal_places=2, help_text='Per student per month, from `ModulePrice`', max_digits=18)),
                ('active_days', models.PositiveSmallIntegerField(help_text='Days of the month the module was entitled')),
                ('days_in_month', models.PositiveSmallIntegerField()),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, help_text='active_count x unit_price x active_days / days_in_month, rounded half-up once', max_digits=18)),
                ('computed_at', models.DateTimeField(help_text='RPT-005: data freshness timestamp')),
                ('active_uniq_marker', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField())),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_charges', to='identity.school')),
            ],
            options={
                'db_table': 'rpt_subscription_charges',
                'indexes': [models.Index(fields=['foundation_id', 'school_id', 'month'], name='rpt_subscri_foundat_73effb_idx')],
                'constraints': [models.UniqueConstraint(fields=('foundation_id', 'school', 'month', 'module_key', 'active_uniq_marker'), name='unique_rpt_subscription_charge_per_school_month_module')],
            },
        ),
    ]
