# Generated by Django 5.1.15 on 2026-09-19 13:14

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_rptparentweeklyactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='rptparentweeklyactivity',
            name='attendance_expected_periods',
            field=models.PositiveIntegerField(blank=True, help_text='Timetable periods that fell in the week and needed attendance', null=True),
        ),
        migrations.AddField(
            model_name='rptparentweeklyactivity',
            name='attendance_submitted_periods',
            field=models.PositiveIntegerField(blank=True, help_text='Of those, periods with attendance submitted', null=True),
        ),
        migrations.AddField(
            model_name='rptparentweeklyactivity',
            name='canteen_active_students',
            field=models.PositiveIntegerField(blank=True, help_text='Counted students with a completed canteen purchase in the week', null=True),
        ),
        migrations.AddField(
            model_name='rptparentweeklyactivity',
            name='collection_billed',
            field=apps.core.fields.MoneyField(blank=True, decimal_places=2, help_text='IDR invoices due in the week (issued, part-paid, paid, written off)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='rptparentweeklyactivity',
            name='collection_collected',
            field=apps.core.fields.MoneyField(blank=True, decimal_places=2, help_text='Of those, settled by the end of the week', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='rptparentweeklyactivity',
            name='gate_samples',
            field=models.PositiveIntegerField(blank=True, help_text='Gate/face device availability samples in operational hours', null=True),
        ),
        migrations.AddField(
            model_name='rptparentweeklyactivity',
            name='gate_up_samples',
            field=models.PositiveIntegerField(blank=True, help_text='Of those, samples where the device was reachable', null=True),
        ),
        migrations.AddField(
            model_name='rptparentweeklyactivity',
            name='health_computed_at',
            field=models.DateTimeField(blank=True, help_text='When the RPT-013 columns were computed; a week computed after it ended is frozen', null=True),
        ),
    ]
