# Generated by Django 5.2.17 on 2026-09-15 00:58

import apps.core.fields
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0005_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(db_index=True, help_text='e.g. SPP_REGULER, UANG_GEDUNG', max_length=32)),
                ('name', models.CharField(help_text='Display label, e.g. SPP Bulanan', max_length=128)),
                ('category', models.CharField(choices=[('SPP', 'SPP (Monthly Tuition)'), ('ENTRY', 'Uang Pangkal (Entry Fee)'), ('ACTIVITY', 'Uang Kegiatan (Activity Fee)'), ('EXAM', 'Uang Ujian (Exam Fee)'), ('UNIFORM', 'Seragam (Uniform)'), ('BOOK', 'Buku Paket (Book)'), ('OTHER', 'Lainnya (Other)')], default='SPP', max_length=32)),
                ('recurrence', models.CharField(choices=[('MONTHLY', 'Bulanan (Monthly)'), ('TERM', 'Per Semester (Term)'), ('ANNUAL', 'Tahunan (Annual)'), ('ONE_OFF', 'Sekali Bayar (One-off)')], default='MONTHLY', max_length=32)),
                ('default_amount', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Default fee amount in standard currency', max_digits=18)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('taxable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_types', to='identity.school')),
            ],
            options={
                'db_table': 'fee_types',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('PERCENT', 'Persentase (Percent)'), ('FIXED', 'Nominal Tetap (Fixed Amount)')], default='PERCENT', max_length=16)),
                ('value', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage (e.g. 10.00) or fixed amount in currency', max_digits=18)),
                ('reason', models.CharField(help_text='Alasan diskon/keringanan, e.g. Beasiswa Tahfidz, Prestasi', max_length=255)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Konsep (Draft)'), ('PENDING_APPROVAL', 'Menunggu Persetujuan (Pending Approval)'), ('APPROVED', 'Disetujui (Approved)'), ('REJECTED', 'Ditolak (Rejected)')], db_index=True, default='DRAFT', max_length=32)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_discounts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='identity.student')),
                ('fee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='finance.feetype')),
            ],
            options={
                'db_table': 'discounts',
            },
        ),
        migrations.CreateModel(
            name='SiblingDiscountPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('child_order', models.PositiveIntegerField(help_text='Child order (2 for 2nd child, 3 for 3rd child, etc.)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage (e.g. 10.00 for 10%)', max_digits=5)),
                ('fee_category', models.CharField(choices=[('SPP', 'SPP (Monthly Tuition)'), ('ENTRY', 'Uang Pangkal (Entry Fee)'), ('ACTIVITY', 'Uang Kegiatan (Activity Fee)'), ('EXAM', 'Uang Ujian (Exam Fee)'), ('UNIFORM', 'Seragam (Uniform)'), ('BOOK', 'Buku Paket (Book)'), ('OTHER', 'Lainnya (Other)')], default='SPP', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sibling_policies', to='identity.school')),
            ],
            options={
                'db_table': 'sibling_discount_policies',
            },
        ),
        migrations.CreateModel(
            name='StudentFeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('start_period', models.CharField(help_text='Effective start period YYYY-MM', max_length=7)),
                ('end_period', models.CharField(blank=True, help_text='Optional end period YYYY-MM', max_length=7, null=True)),
                ('source', models.CharField(choices=[('STUDENT', 'Siswa Individu (Individual Student)'), ('CLASS', 'Rombel Kelas (Class Group)'), ('GRADE', 'Tingkat Kelas (Grade Level)')], default='STUDENT', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assignments', to='finance.feetype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_assignments', to='identity.student')),
            ],
            options={
                'db_table': 'student_fee_assignments',
            },
        ),
        migrations.CreateModel(
            name='FeePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('academic_year', models.CharField(help_text='e.g. 2026/2027', max_length=16)),
                ('name', models.CharField(help_text='e.g. Paket SPP & Kegiatan Kelas 7', max_length=128)),
                ('grade_levels', models.JSONField(default=list, help_text="List of grade level strings e.g. ['7', '8', '9']")),
                ('lines', models.JSONField(default=list, help_text='List of fee line items [{fee_type_id, amount, currency}]')),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_plans', to='identity.school')),
            ],
            options={
                'db_table': 'fee_plans',
                'indexes': [models.Index(fields=['foundation_id', 'school', 'academic_year'], name='fee_plans_foundat_334574_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='feetype',
            index=models.Index(fields=['foundation_id', 'school', 'category'], name='fee_types_foundat_63456d_idx'),
        ),
        migrations.AddConstraint(
            model_name='feetype',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'school', 'code'), name='unique_school_fee_type_code'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['foundation_id', 'student', 'status'], name='discounts_foundat_9fe0f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='siblingdiscountpolicy',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'school', 'child_order', 'fee_category'), name='unique_school_sibling_policy'),
        ),
        migrations.AddIndex(
            model_name='studentfeeassignment',
            index=models.Index(fields=['foundation_id', 'student', 'start_period'], name='student_fee_foundat_a17f55_idx'),
        ),
    ]
