# Generated by Django 5.2.17 on 2026-09-15 01:04

import apps.core.fields
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('identity', '0005_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('number', models.CharField(db_index=True, help_text='Format: INV/{school_code}/{YYYY}/{NNNNNN}', max_length=64, unique=True)),
                ('period', models.CharField(db_index=True, help_text='Billing period format YYYY-MM (e.g. 2026-10)', max_length=7)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('subtotal', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of lines before discounts', max_digits=18)),
                ('discount', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Total discounts applied', max_digits=18)),
                ('rounding', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='PEMBULATAN line adjustment (FIN-008c, CUR-019)', max_digits=18)),
                ('total', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Final amount payable (subtotal - discount + rounding)', max_digits=18)),
                ('paid', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative settled payments', max_digits=18)),
                ('currency', models.CharField(default='IDR', help_text='Invoice currency (CUR-002, CUR-008)', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Konsep (Draft)'), ('ISSUED', 'Diterbitkan (Issued)'), ('PARTIALLY_PAID', 'Dibayar Sebagian (Partially Paid)'), ('PAID', 'Lunas (Paid)'), ('CANCELLED', 'Dibatalkan (Cancelled)'), ('WRITTEN_OFF', 'Dihapusbukukan (Written Off)')], db_index=True, default='ISSUED', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='identity.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='identity.student')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(help_text='Line code, e.g. SPP_REGULER or PEMBULATAN', max_length=32)),
                ('description', models.CharField(help_text='Display item description', max_length=255)),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Base line item amount', max_digits=18)),
                ('discount', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Discount deduction on this line', max_digits=18)),
                ('subtotal', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Net line total (amount - discount)', max_digits=18)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('fee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='finance.feetype')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.invoice')),
            ],
            options={
                'db_table': 'invoice_lines',
            },
        ),
        migrations.CreateModel(
            name='InvoiceNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('year', models.PositiveIntegerField(help_text='Calendar year (e.g. 2026)')),
                ('last_number', models.PositiveIntegerField(default=0, help_text='Latest allocated sequence number')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_sequences', to='identity.school')),
            ],
            options={
                'db_table': 'invoice_number_sequences',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['foundation_id', 'school', 'period'], name='invoices_foundat_3ebefe_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['foundation_id', 'student', 'status'], name='invoices_foundat_fafae1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['foundation_id', 'due_date', 'status'], name='invoices_foundat_88b00a_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'student', 'period'), name='unique_active_invoice_per_student_period'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['foundation_id', 'invoice'], name='invoice_lin_foundat_7f2b06_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoicenumbersequence',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'school', 'year'), name='unique_school_year_invoice_sequence'),
        ),
    ]
