# Generated by Django 5.2.17 on 2026-09-15 01:21

import apps.core.fields
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_invoice_invoiceline_invoicenumbersequence_and_more'),
        ('identity', '0005_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('number', models.CharField(db_index=True, help_text='Format: JRN/{school_code}/{YYYY}/{NNNNNN}', max_length=64, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('ref_type', models.CharField(help_text='e.g. INVOICE, PAYMENT, REVENUE_RECOGNITION, REFUND', max_length=32)),
                ('ref_id', models.CharField(help_text='Primary identifier of the triggering entity', max_length=64)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_journals', to='identity.school')),
            ],
            options={
                'db_table': 'ledger_journals',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('account_code', models.CharField(db_index=True, help_text='e.g. 1100, 1200, 2100, 4100', max_length=32)),
                ('account_name', models.CharField(max_length=128)),
                ('debit', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('ref_type', models.CharField(blank=True, max_length=32, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=64, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='identity.school')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance.ledgerjournal')),
            ],
            options={
                'db_table': 'ledger_entries',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('method', models.CharField(choices=[('VA', 'Virtual Account'), ('QRIS', 'QRIS'), ('MANUAL', 'Transfer Manual (Manual Transfer)'), ('CASH', 'Tunai di Sekolah (Cash at School)')], default='VA', max_length=32)),
                ('channel', models.CharField(help_text='e.g. BCA_VA, QRIS_GOPAY, CASHIER, MANDIRI_TRANSFER', max_length=64)),
                ('reference', models.CharField(db_index=True, help_text='Unique payment reference e.g. PAY/SDIT01/2026/000001', max_length=64, unique=True)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Gateway order_id or transaction ID', max_length=128, null=True)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Pembayaran (Pending)'), ('SETTLED', 'Berhasil/Lunas (Settled)'), ('FAILED', 'Gagal (Failed)'), ('CANCELLED', 'Dibatalkan (Cancelled)'), ('PENDING_VERIFICATION', 'Menunggu Verifikasi (Pending Verification)'), ('REJECTED', 'Ditolak (Rejected)')], db_index=True, default='PENDING', max_length=32)),
                ('fee', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Gateway or transaction fee', max_digits=18)),
                ('net', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Net amount received by school (amount - fee)', max_digits=18)),
                ('receipt_number', models.CharField(blank=True, help_text='Receipt number e.g. RCP/SDIT01/2026/000001', max_length=64, null=True)),
                ('proof_file', models.CharField(blank=True, help_text='Proof upload file path', max_length=512, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.invoice')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='identity.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='identity.student')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.invoice')),
                ('invoice_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.invoiceline')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.payment')),
            ],
            options={
                'db_table': 'payment_allocations',
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('method', models.CharField(choices=[('VA', 'Virtual Account'), ('QRIS', 'QRIS'), ('MANUAL', 'Transfer Manual (Manual Transfer)'), ('CASH', 'Tunai di Sekolah (Cash at School)')], default='VA', max_length=32)),
                ('provider', models.CharField(default='MIDTRANS', help_text='MIDTRANS, XENDIT, MOCK, MANUAL', max_length=32)),
                ('va_bank', models.CharField(blank=True, help_text='Bank code for VA, e.g. BCA, MANDIRI', max_length=32, null=True)),
                ('va_number', models.CharField(blank=True, max_length=64, null=True)),
                ('qris_payload', models.TextField(blank=True, null=True)),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Pembayaran (Pending)'), ('COMPLETED', 'Selesai (Completed)'), ('EXPIRED', 'Kedaluwarsa (Expired)'), ('CANCELLED', 'Dibatalkan (Cancelled)')], db_index=True, default='PENDING', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='finance.invoice')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='identity.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='identity.student')),
            ],
            options={
                'db_table': 'payment_intents',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.paymentintent'),
        ),
        migrations.CreateModel(
            name='PaymentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sequence_type', models.CharField(help_text='PAYMENT, RECEIPT, JOURNAL', max_length=16)),
                ('year', models.PositiveIntegerField(help_text='Calendar year e.g. 2026')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_sequences', to='identity.school')),
            ],
            options={
                'db_table': 'payment_sequences',
            },
        ),
        migrations.CreateModel(
            name='StudentCreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('balance', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_balances', to='identity.student')),
            ],
            options={
                'db_table': 'student_credit_balances',
            },
        ),
        migrations.CreateModel(
            name='StudentVirtualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('bank', models.CharField(help_text='e.g. BCA, MANDIRI, BRI, BNI, PERMATA', max_length=32)),
                ('va_number', models.CharField(db_index=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='virtual_accounts', to='identity.student')),
            ],
            options={
                'db_table': 'student_virtual_accounts',
            },
        ),
        migrations.AddIndex(
            model_name='ledgerjournal',
            index=models.Index(fields=['foundation_id', 'school', 'occurred_at'], name='ledger_jour_foundat_2f9eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerjournal',
            index=models.Index(fields=['foundation_id', 'ref_type', 'ref_id'], name='ledger_jour_foundat_bb970a_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['foundation_id', 'school', 'account_code'], name='ledger_entr_foundat_09be19_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['foundation_id', 'journal'], name='ledger_entr_foundat_150904_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['foundation_id', 'occurred_at'], name='ledger_entr_foundat_6c042d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['foundation_id', 'payment'], name='payment_all_foundat_bb3391_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['foundation_id', 'invoice'], name='payment_all_foundat_969d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['foundation_id', 'school', 'status'], name='payment_int_foundat_613f46_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['foundation_id', 'student', 'status'], name='payment_int_foundat_baddec_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['foundation_id', 'va_number'], name='payment_int_foundat_0fb433_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['foundation_id', 'school', 'status'], name='payments_foundat_b630bd_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['foundation_id', 'student', 'status'], name='payments_foundat_bef1a1_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['foundation_id', 'paid_at'], name='payments_foundat_988d87_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('foundation_id', 'external_id'), name='unique_foundation_payment_external_id'),
        ),
        migrations.AddConstraint(
            model_name='paymentsequence',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'school', 'sequence_type', 'year'), name='unique_school_sequence_type_year'),
        ),
        migrations.AddConstraint(
            model_name='studentcreditbalance',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'student', 'currency'), name='unique_foundation_student_currency_credit_balance'),
        ),
        migrations.AddIndex(
            model_name='studentvirtualaccount',
            index=models.Index(fields=['foundation_id', 'student', 'bank'], name='student_vir_foundat_b75d5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentvirtualaccount',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'bank', 'va_number'), name='unique_foundation_bank_va_number'),
        ),
    ]
