# Generated by Django 5.1.15 on 2026-09-15 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payments_and_ledger'),
        ('identity', '0005_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolQrisConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('qris_image_key', models.CharField(blank=True, default='', help_text='MEDIA_ROOT-relative key of the uploaded static QRIS image', max_length=512)),
                ('qris_payload', models.TextField(blank=True, default='', help_text='Raw QRIS string, if the school has it in addition to/instead of an image')),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='qris_config', to='identity.school')),
            ],
            options={
                'db_table': 'school_qris_configs',
            },
        ),
    ]
