# Generated by Django 5.2.17 on 2026-09-15 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_schoolqrisconfig'),
        ('identity', '0005_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolArrearsPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ladder_days', models.JSONField(blank=True, default=list, help_text='Offsets in days relative to due date, e.g. [-3, 0, 3, 7, 14, 30]')),
                ('is_active', models.BooleanField(default=True)),
                ('payment_deep_link_base', models.CharField(default='/pay/{invoice_id}', help_text='Base URL or template for payment link in reminders (FIN-028)', max_length=255)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='arrears_policy', to='identity.school')),
            ],
            options={
                'db_table': 'school_arrears_policies',
            },
        ),
    ]
