# Generated by Django 5.2.17 on 2026-09-15 10:36

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_schoolarrearspolicy'),
        ('identity', '0005_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceWriteOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, help_text='Nominal piutang yang dihapusbukukan', max_digits=18)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('reason', models.TextField(help_text='Alasan penghapusbukuan piutang tak tertagih')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Persetujuan (Pending Approval)'), ('APPROVED', 'Disetujui (Approved)'), ('REJECTED', 'Ditolak (Rejected)')], db_index=True, default='PENDING', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_write_off_requests', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_off_requests', to='finance.invoice')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_off_requests', to='finance.ledgerjournal')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_write_off_requests', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_off_requests', to='identity.school')),
            ],
            options={
                'db_table': 'invoice_write_off_requests',
                'indexes': [models.Index(fields=['foundation_id', 'school_id', 'status'], name='invoice_wri_foundat_fc3114_idx'), models.Index(fields=['foundation_id', 'invoice_id'], name='invoice_wri_foundat_5a4cd8_idx')],
            },
        ),
    ]
