# Generated by Django 5.2.17 on 2026-09-15 11:55

import apps.core.fields
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_bad_debt_write_off_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('installment_no', models.PositiveSmallIntegerField(help_text='Installment index starting from 1')),
                ('due_date', models.DateField(help_text='Due date for this installment')),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Scheduled installment amount (CUR-018)', max_digits=18)),
                ('paid_amount', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative settled payments on this installment', max_digits=18)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Pembayaran (Pending)'), ('PARTIALLY_PAID', 'Dibayar Sebagian (Partially Paid)'), ('PAID', 'Lunas (Paid)'), ('CANCELLED', 'Dibatalkan (Cancelled)')], db_index=True, default='PENDING', max_length=32)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.invoice')),
            ],
            options={
                'db_table': 'invoice_installments',
                'indexes': [models.Index(fields=['foundation_id', 'invoice', 'status'], name='invoice_ins_foundat_a21d9a_idx'), models.Index(fields=['foundation_id', 'due_date', 'status'], name='invoice_ins_foundat_ed8048_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'invoice', 'installment_no'), name='unique_invoice_installment_no')],
            },
        ),
    ]
