# Generated by Django 5.2.17 on 2026-09-15 12:58

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_invoiceinstallment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewaySettlementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider', models.CharField(db_index=True, help_text='Payment provider: MIDTRANS, XENDIT, MOCK', max_length=32)),
                ('settlement_date', models.DateField(db_index=True, help_text='The settlement calendar date this batch covers (YYYY-MM-DD)')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Proses (Pending)'), ('PROCESSING', 'Sedang Diproses (Processing)'), ('COMPLETED', 'Selesai (Completed)'), ('FAILED', 'Gagal (Failed)'), ('PARTIAL', 'Sebagian Berhasil (Partial)')], db_index=True, default='PENDING', max_length=16)),
                ('fetched_at', models.DateTimeField(blank=True, help_text='Timestamp when gateway data was successfully fetched', null=True)),
                ('total_records', models.PositiveIntegerField(default=0, help_text='Total settlement records returned by the gateway')),
                ('matched_count', models.PositiveIntegerField(default=0, help_text='Records matched to an existing Payment and auto-settled')),
                ('missing_count', models.PositiveIntegerField(default=0, help_text='Gateway records with no matching Payment in EduCore')),
                ('mismatch_count', models.PositiveIntegerField(default=0, help_text='Records where gateway amount differs from Payment amount')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error traceback or message if the batch run failed')),
                ('raw_summary', models.JSONField(blank=True, default=dict, help_text='Provider-specific aggregate totals from gateway response')),
            ],
            options={
                'db_table': 'gateway_settlement_batches',
                'indexes': [models.Index(fields=['foundation_id', 'settlement_date'], name='gateway_set_foundat_59bd8a_idx'), models.Index(fields=['foundation_id', 'provider', 'status'], name='gateway_set_foundat_c28571_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'provider', 'settlement_date'), name='unique_foundation_provider_settlement_date')],
            },
        ),
        migrations.CreateModel(
            name='PaymentDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('external_id', models.CharField(db_index=True, help_text='Gateway transaction or reference ID', max_length=128)),
                ('discrepancy_type', models.CharField(choices=[('MISSING_IN_SYSTEM', 'Ada di Gateway, Tidak Ada di Sistem (Missing in System)'), ('AMOUNT_MISMATCH', 'Jumlah Tidak Sesuai (Amount Mismatch)'), ('DUPLICATE', 'Duplikat (Duplicate Entry)'), ('EXTRA_IN_SYSTEM', 'Ada di Sistem, Tidak Ada di Gateway (Extra in System)')], db_index=True, max_length=32)),
                ('gateway_amount', apps.core.fields.MoneyField(decimal_places=2, default=0, help_text='Gross amount reported by the gateway', max_digits=18)),
                ('gateway_fee', apps.core.fields.MoneyField(decimal_places=2, default=0, help_text='Fee reported by the gateway', max_digits=18)),
                ('gateway_net', apps.core.fields.MoneyField(decimal_places=2, default=0, help_text='Net amount reported by the gateway (amount - fee)', max_digits=18)),
                ('system_amount', apps.core.fields.MoneyField(blank=True, decimal_places=2, help_text='Amount recorded in the EduCore Payment record (if matched)', max_digits=18, null=True)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('channel', models.CharField(blank=True, default='', max_length=64)),
                ('bank', models.CharField(blank=True, default='', max_length=32)),
                ('gateway_settled_at', models.DateTimeField(blank=True, help_text='Timestamp of settlement according to the gateway', null=True)),
                ('resolution', models.CharField(choices=[('PENDING', 'Menunggu Tindak Lanjut (Pending Review)'), ('AUTO_SETTLED', 'Diselesaikan Otomatis (Auto-settled)'), ('MANUAL_SETTLED', 'Diselesaikan Manual (Manually Settled)'), ('WAIVED', 'Diabaikan (Waived)'), ('ESCALATED', 'Diteruskan ke Tim Keuangan (Escalated)')], db_index=True, default='PENDING', max_length=32)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('raw_gateway_record', models.JSONField(blank=True, default=dict, help_text='Unmodified gateway settlement record for audit trail')),
                ('batch', models.ForeignKey(help_text='Parent batch this discrepancy belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='finance.gatewaysettlementbatch')),
                ('payment', models.ForeignKey(blank=True, help_text='Matched Payment record, if found (null for MISSING_IN_SYSTEM)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies', to='finance.payment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_discrepancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_discrepancies',
                'indexes': [models.Index(fields=['foundation_id', 'batch', 'discrepancy_type'], name='payment_dis_foundat_8297b7_idx'), models.Index(fields=['foundation_id', 'external_id'], name='payment_dis_foundat_75fd4a_idx'), models.Index(fields=['foundation_id', 'resolution'], name='payment_dis_foundat_b7d1d1_idx')],
            },
        ),
    ]
