# Generated by Django 5.1.15 on 2026-09-15 13:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_add_gateway_reconciliation_models'),
        ('identity', '0005_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolConvenienceFeePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('allocation', models.CharField(choices=[('ABSORBED_BY_SCHOOL', 'Ditanggung Sekolah (Absorbed by School)'), ('PASSED_TO_PARENT', 'Dibebankan ke Orang Tua (Passed to Parent)')], default='PASSED_TO_PARENT', max_length=32)),
                ('fee_type', models.CharField(choices=[('FIXED', 'Nominal Tetap (Fixed Amount)'), ('PERCENTAGE', 'Persentase (Percentage)')], default='FIXED', max_length=16)),
                ('fee_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Fixed amount (in the invoice's currency) or percentage (e.g. 1.50 for 1.5%), per fee_type", max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='convenience_fee_policy', to='identity.school')),
            ],
            options={
                'db_table': 'school_convenience_fee_policies',
            },
        ),
    ]
