# Generated by Django 5.1.15 on 2026-09-15 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_schoolconveniencefeepolicy'),
        ('identity', '0005_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSftpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('bank_code', models.CharField(help_text='e.g. BCA, MANDIRI, BRI', max_length=32)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=22)),
                ('username', models.CharField(max_length=128)),
                ('remote_directory', models.CharField(default='/', help_text='Remote directory to list/pull statement files from', max_length=512)),
                ('file_format', models.CharField(choices=[('MT940', 'SWIFT MT940'), ('CAMT053', 'ISO 20022 CAMT.053')], default='MT940', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_sftp_configs', to='identity.school')),
            ],
            options={
                'db_table': 'bank_sftp_configs',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'school', 'bank_code'), name='unique_foundation_school_bank_sftp_config')],
            },
        ),
    ]
