# Generated by Django 5.1.15 on 2026-09-15 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_banksftpconfig'),
        ('identity', '0005_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='banksftpconfig',
            name='unique_foundation_school_bank_sftp_config',
        ),
        migrations.RemoveConstraint(
            model_name='gatewaysettlementbatch',
            name='unique_foundation_provider_settlement_date',
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_active_invoice_per_student_period',
        ),
        migrations.RemoveConstraint(
            model_name='invoiceinstallment',
            name='unique_invoice_installment_no',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='unique_foundation_payment_external_id',
        ),
        migrations.AddField(
            model_name='banksftpconfig',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='gatewaysettlementbatch',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='invoice',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='invoiceinstallment',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddConstraint(
            model_name='banksftpconfig',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'school', 'bank_code', 'active_uniq_marker'), name='unique_foundation_school_bank_sftp_config'),
        ),
        migrations.AddConstraint(
            model_name='gatewaysettlementbatch',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'provider', 'settlement_date', 'active_uniq_marker'), name='unique_foundation_provider_settlement_date'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'student', 'period', 'active_uniq_marker'), name='unique_active_invoice_per_student_period'),
        ),
        migrations.AddConstraint(
            model_name='invoiceinstallment',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'invoice', 'installment_no', 'active_uniq_marker'), name='unique_invoice_installment_no'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'external_id'), name='unique_foundation_payment_external_id'),
        ),
    ]
