# Generated by Django 5.2.17 on 2026-09-16 00:59

import apps.core.fields
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_remove_banksftpconfig_unique_foundation_school_bank_sftp_config_and_more'),
        ('identity', '0005_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('period', models.CharField(db_index=True, help_text='Format YYYY-MM, e.g. 2026-08', max_length=7)),
                ('status', models.CharField(choices=[('OPEN', 'Terbuka'), ('CLOSED', 'Ditutup')], db_index=True, default='OPEN', max_length=16)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('total_journals', models.PositiveIntegerField(default=0)),
                ('total_debit', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_credit', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('closing_notes', models.TextField(blank=True, default='')),
                ('active_uniq_marker', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField())),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_fiscal_periods', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reopened_fiscal_periods', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_periods', to='identity.school')),
            ],
            options={
                'db_table': 'finance_fiscal_periods',
                'indexes': [models.Index(fields=['foundation_id', 'school', 'period'], name='finance_fis_foundat_c2f955_idx'), models.Index(fields=['foundation_id', 'status'], name='finance_fis_foundat_a967f5_idx')],
                'constraints': [models.UniqueConstraint(fields=('foundation_id', 'school', 'period', 'active_uniq_marker'), name='unique_school_fiscal_period')],
            },
        ),
    ]
