# Generated by Django 5.2.17 on 2026-09-16 01:31

import apps.core.fields
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_fiscalperiod'),
        ('identity', '0005_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Nominal pengembalian dana', max_digits=18)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('reason', models.TextField(help_text='Alasan pengembalian dana')),
                ('destination_bank_name', models.CharField(help_text='Nama bank penerima (e.g. BCA, MANDIRI)', max_length=64)),
                ('destination_account_number', models.CharField(help_text='Nomor rekening tujuan', max_length=64)),
                ('destination_account_holder', models.CharField(help_text='Nama pemilik rekening tujuan', max_length=128)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Menunggu Persetujuan (Pending Approval)'), ('APPROVED', 'Disetujui (Approved)'), ('REJECTED', 'Ditolak (Rejected)'), ('EXECUTED', 'Berhasil Dikirim (Executed)'), ('CANCELLED', 'Dibatalkan (Cancelled)')], db_index=True, default='PENDING_APPROVAL', max_length=32)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('payout_reference', models.CharField(blank=True, default='', help_text='Gateway payout ID atau referensi transfer bank', max_length=128)),
                ('payout_proof_file', models.CharField(blank=True, default='', help_text='File path bukti transfer pengembalian dana', max_length=512)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_refunds', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executed_refunds', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, help_text='Compensating double-entry ledger journal (FIN-020)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='finance.ledgerjournal')),
                ('payment', models.ForeignKey(help_text='The settled payment being refunded', on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='finance.payment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_refunds', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='identity.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='identity.student')),
            ],
            options={
                'db_table': 'refunds',
                'indexes': [models.Index(fields=['foundation_id', 'school', 'status'], name='refunds_foundat_549ef7_idx'), models.Index(fields=['foundation_id', 'payment'], name='refunds_foundat_7fdcbb_idx'), models.Index(fields=['foundation_id', 'student'], name='refunds_foundat_224e63_idx'), models.Index(fields=['foundation_id', 'created_at'], name='refunds_foundat_59ca0b_idx')],
            },
        ),
    ]
