# Generated by Django 5.1.15 on 2026-09-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='waived',
            field=models.BooleanField(default=False, help_text='Set when a FIXED-type discount (waiver) is approved against this line (spec/03 FND-007 AC#2, spec/06 §2)'),
        ),
    ]
