# Generated by Django 5.2.17 on 2026-09-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_invoiceline_waived'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_pdf_key',
            field=models.CharField(blank=True, help_text='GCS object key for rendered receipt document (PAR-009, FIN-019)', max_length=512, null=True),
        ),
    ]
