# Generated by Django 5.2.17 on 2026-09-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_payment_receipt_pdf_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('system', models.CharField(choices=[('ACCURATE', 'CPSSoft Accurate Online'), ('JURNAL', 'Mekari Jurnal.id')], db_index=True, max_length=32)),
                ('internal_code', models.CharField(choices=[('1100', 'Kas / Bank'), ('1200', 'Piutang SPP & Biaya'), ('2100', 'Pendapatan Diterima di Muka'), ('2200', 'Saldo Deposit Siswa'), ('4100', 'Pendapatan SPP'), ('4200', 'Pendapatan Lain-lain'), ('5100', 'Beban Transaksi & Gateway'), ('5200', 'Beban Potongan & Keringanan'), ('5300', 'Beban / Pendapatan Pembulatan'), ('5400', 'Beban Piutang Tak Tertagih (Bad Debt)')], db_index=True, help_text='Kode akun internal EduCore (Chart of Accounts)', max_length=32)),
                ('external_code', models.CharField(help_text='Kode akun pada sistem buku besar eksternal (Accurate / Jurnal)', max_length=64)),
                ('external_name', models.CharField(blank=True, default='', help_text='Nama akun pada sistem buku besar eksternal (opsional)', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('active_uniq_marker', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField())),
            ],
            options={
                'db_table': 'external_account_mappings',
                'ordering': ['system', 'internal_code'],
                'indexes': [models.Index(fields=['foundation_id', 'system', 'internal_code'], name='external_ac_foundat_073437_idx')],
                'constraints': [models.UniqueConstraint(fields=('foundation_id', 'system', 'internal_code', 'active_uniq_marker'), name='unique_external_account_mapping')],
            },
        ),
    ]
