# Generated by Django 5.2.17 on 2026-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foundation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('legal_name', models.CharField(help_text='Legal registered name, e.g. Yayasan Pendidikan Islam Al-Hikmah', max_length=255)),
                ('brand_name', models.CharField(help_text='Public-facing brand name, e.g. Al-Hikmah Nusantara', max_length=128)),
                ('npwp', models.CharField(blank=True, default='', help_text='Indonesian tax identification number (Nomor Pokok Wajib Pajak)', max_length=32)),
                ('address', models.TextField(blank=True, default='', help_text='Official registered address')),
                ('timezone', models.CharField(default='Asia/Jakarta', help_text='Default timezone: Asia/Jakarta, Asia/Makassar, or Asia/Jayapura', max_length=32)),
                ('reporting_currency', models.CharField(default='IDR', help_text='Currency for consolidated reporting (CUR-007)', max_length=3)),
                ('plan_tier', models.CharField(choices=[('STARTER', 'Starter'), ('STANDARD', 'Standard'), ('ENTERPRISE', 'Enterprise')], default='STANDARD', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yayasan',
                'verbose_name_plural': 'Daftar Yayasan',
                'db_table': 'foundations',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='e.g. SMP Al-Hikmah Nusantara', max_length=128)),
                ('npsn', models.CharField(db_index=True, help_text='Nomor Pokok Sekolah Nasional (8 digits)', max_length=16, unique=True)),
                ('level', models.CharField(choices=[('SD', 'SD (Sekolah Dasar)'), ('SMP', 'SMP (Sekolah Menengah Pertama)'), ('SMA', 'SMA (Sekolah Menengah Atas)'), ('SMK', 'SMK (Sekolah Menengah Kejuruan)'), ('MI', 'MI (Madrasah Ibtidaiyah)'), ('MTs', 'MTs (Madrasah Tsanawiyah)'), ('MA', 'MA (Madrasah Aliyah)')], max_length=16)),
                ('curriculum', models.CharField(default='KURIKULUM_MERDEKA', help_text='e.g. KURIKULUM_MERDEKA, K13, CAMBRIDGE, IB', max_length=64)),
                ('timezone', models.CharField(default='Asia/Jakarta', max_length=32)),
                ('base_currency', models.CharField(default='IDR', help_text='School base currency (CUR-007)', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sekolah',
                'verbose_name_plural': 'Daftar Sekolah',
                'db_table': 'schools',
                'indexes': [models.Index(fields=['foundation_id', 'level'], name='schools_foundat_55024b_idx'), models.Index(fields=['foundation_id', 'is_active'], name='schools_foundat_33b719_idx')],
            },
        ),
    ]
