# Generated by Django 5.2.17 on 2026-09-14 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foundation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('legal_name', models.CharField(help_text='Legal registered name, e.g. Yayasan Pendidikan Islam Al-Hikmah', max_length=255)),
                ('brand_name', models.CharField(help_text='Public-facing brand name, e.g. Al-Hikmah Nusantara', max_length=128)),
                ('npwp', models.CharField(blank=True, default='', help_text='Nomor Pokok Wajib Pajak', max_length=32)),
                ('address', models.TextField(blank=True, default='', help_text='Official registered address')),
                ('timezone', models.CharField(default='Asia/Jakarta', help_text='Default timezone: Asia/Jakarta, Asia/Makassar, or Asia/Jayapura', max_length=32)),
                ('reporting_currency', models.CharField(default='IDR', help_text='Currency for consolidated reporting (CUR-007)', max_length=3)),
                ('plan_tier', models.CharField(choices=[('STARTER', 'Starter'), ('STANDARD', 'Standard'), ('ENTERPRISE', 'Enterprise')], default='STANDARD', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yayasan',
                'verbose_name_plural': 'Daftar Yayasan',
                'db_table': 'foundations',
            },
        ),
        migrations.CreateModel(
            name='OTPChallenge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone_e164', models.CharField(db_index=True, max_length=20)),
                ('code_hash', models.CharField(help_text='Hashed 6-digit OTP code', max_length=128)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'otp_challenges',
                'indexes': [models.Index(fields=['phone_e164', 'created_at'], name='otp_challen_phone_e_c7d6f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nik', models.CharField(blank=True, db_index=True, help_text='Nomor Induk Kependudukan (16 digits)', max_length=16, null=True)),
                ('full_name', models.CharField(help_text='Full legal name per birth certificate / KTP', max_length=128)),
                ('dob', models.DateField(blank=True, help_text='Tanggal lahir', null=True)),
                ('gender', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='', max_length=1)),
                ('address', models.TextField(blank=True, default='', help_text='Alamat domisili lengkap')),
            ],
            options={
                'verbose_name': 'Data Pribadi (PII)',
                'verbose_name_plural': 'Data Pribadi (PII)',
                'db_table': 'persons',
                'indexes': [models.Index(fields=['foundation_id', 'nik'], name='persons_foundat_dc36b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='e.g. SMP Al-Hikmah Nusantara', max_length=128)),
                ('npsn', models.CharField(db_index=True, help_text='Nomor Pokok Sekolah Nasional (8 digits)', max_length=16, unique=True)),
                ('level', models.CharField(choices=[('SD', 'SD (Sekolah Dasar)'), ('SMP', 'SMP (Sekolah Menengah Pertama)'), ('SMA', 'SMA (Sekolah Menengah Atas)'), ('SMK', 'SMK (Sekolah Menengah Kejuruan)'), ('MI', 'MI (Madrasah Ibtidaiyah)'), ('MTs', 'MTs (Madrasah Tsanawiyah)'), ('MA', 'MA (Madrasah Aliyah)')], max_length=16)),
                ('curriculum', models.CharField(default='KURIKULUM_MERDEKA', max_length=64)),
                ('timezone', models.CharField(default='Asia/Jakarta', max_length=32)),
                ('base_currency', models.CharField(default='IDR', help_text='School base currency (CUR-007)', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sekolah',
                'verbose_name_plural': 'Daftar Sekolah',
                'db_table': 'schools',
                'indexes': [models.Index(fields=['foundation_id', 'level'], name='schools_foundat_55024b_idx'), models.Index(fields=['foundation_id', 'is_active'], name='schools_foundat_33b719_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('phone_e164', models.CharField(db_index=True, help_text='Nomor HP format E.164 (+62...)', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('full_name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=32)),
                ('mfa_secret', models.CharField(blank=True, default='', help_text='Base32 TOTP secret for staff MFA', max_length=64)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Pengguna',
                'verbose_name_plural': 'Daftar Pengguna',
                'db_table': 'users',
                'indexes': [models.Index(fields=['foundation_id', 'status'], name='users_foundat_9d3174_idx'), models.Index(fields=['foundation_id', 'email'], name='users_foundat_b35d52_idx')],
            },
        ),
    ]
