# Generated by Django 5.2.17 on 2026-09-14 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('foundation_admin', 'Foundation Admin'), ('school_admin', 'School Admin'), ('finance_officer', 'Finance Officer'), ('teacher', 'Teacher'), ('counsellor', 'Counsellor'), ('parent', 'Parent')], db_index=True, max_length=32)),
                ('scope_type', models.CharField(choices=[('FOUNDATION', 'Foundation'), ('SCHOOL', 'School')], db_index=True, default='SCHOOL', max_length=16)),
                ('scope_id', models.BigIntegerField(db_index=True, help_text='ID of Foundation if scope_type=FOUNDATION, or School if scope_type=SCHOOL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Penugasan Peran',
                'verbose_name_plural': 'Daftar Penugasan Peran',
                'db_table': 'role_assignments',
                'indexes': [models.Index(fields=['foundation_id', 'user', 'role'], name='role_assign_foundat_7bdb27_idx'), models.Index(fields=['foundation_id', 'scope_type', 'scope_id'], name='role_assign_foundat_c4d9d1_idx')],
                'constraints': [models.UniqueConstraint(fields=('foundation_id', 'user', 'role', 'scope_type', 'scope_id'), name='unique_user_role_scope')],
            },
        ),
    ]
