# Generated by Django 5.2.17 on 2026-09-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_roleassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundationEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('school_id', models.BigIntegerField(blank=True, db_index=True, help_text='Null for foundation-wide default, or specific school ID', null=True)),
                ('module_key', models.CharField(choices=[('academic', 'Academic'), ('attendance', 'Attendance'), ('finance', 'Finance'), ('wallet', 'Wallet / Canteen'), ('campus_life', 'Campus Life'), ('payroll', 'Payroll'), ('analytics', 'Analytics'), ('hardware', 'Hardware & IoT')], db_index=True, max_length=32)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('limits', models.JSONField(blank=True, default=dict, help_text='Plan tier limits or quotas (JSON)')),
            ],
            options={
                'verbose_name': 'Hak Akses Modul',
                'verbose_name_plural': 'Daftar Hak Akses Modul',
                'db_table': 'foundation_entitlements',
                'indexes': [models.Index(fields=['foundation_id', 'module_key'], name='foundation__foundat_0585fa_idx'), models.Index(fields=['foundation_id', 'school_id', 'module_key'], name='foundation__foundat_13f5ac_idx')],
            },
        ),
    ]
