# Generated by Django 5.2.17 on 2026-09-14 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_foundationentitlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('occupation', models.CharField(blank=True, default='', help_text='Pekerjaan wali murid (e.g. Pegawai Swasta, Wiraswasta, Guru)', max_length=128)),
                ('person', models.ForeignKey(help_text='Reference to Person PII vault (spec/02 §2)', on_delete=django.db.models.deletion.PROTECT, related_name='guardian_profiles', to='identity.person')),
                ('user', models.ForeignKey(blank=True, help_text='Associated user account for mobile login (null if not yet invited/registered)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wali Murid',
                'verbose_name_plural': 'Daftar Wali Murid',
                'db_table': 'guardians',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nisn', models.CharField(blank=True, db_index=True, help_text='Nomor Induk Siswa Nasional (10 digits)', max_length=10, null=True)),
                ('nis', models.CharField(db_index=True, help_text='Nomor Induk Siswa (internal school registration number)', max_length=32)),
                ('photo_key', models.CharField(blank=True, default='', help_text='Local filesystem key / relative path to student profile picture', max_length=255)),
                ('status', models.CharField(choices=[('PROSPECT', 'Calon Siswa (Prospect)'), ('ACTIVE', 'Aktif (Active)'), ('INACTIVE', 'Nonaktif (Inactive)'), ('GRADUATED', 'Lulus (Graduated)'), ('TRANSFERRED_OUT', 'Pindah Keluar (Transferred Out)')], db_index=True, default='PROSPECT', help_text='Current enrollment status (IAM-019)', max_length=32)),
                ('person', models.ForeignKey(help_text='Reference to Person PII vault (spec/02 §2, spec/14 §4)', on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='identity.person')),
                ('school', models.ForeignKey(help_text='The school/madrasah where the student is currently enrolled', on_delete=django.db.models.deletion.PROTECT, related_name='students', to='identity.school')),
            ],
            options={
                'verbose_name': 'Siswa',
                'verbose_name_plural': 'Daftar Siswa',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='GuardianLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('relation', models.CharField(choices=[('FATHER', 'Ayah (Father)'), ('MOTHER', 'Ibu (Mother)'), ('GUARDIAN', 'Wali (Guardian)')], default='GUARDIAN', help_text='Hubungan kekeluargaan (Ayah, Ibu, atau Wali)', max_length=16)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this guardian is the primary contact for communications')),
                ('can_pickup', models.BooleanField(default=True, help_text='Whether this guardian is authorized for student campus pickup')),
                ('financial_responsible', models.BooleanField(default=False, help_text='Whether this guardian receives invoices and can view financial arrears (IAM-015)')),
                ('guardian', models.ForeignKey(help_text='The parent or legal guardian', on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='identity.guardian')),
                ('student', models.ForeignKey(help_text='The linked student', on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='identity.student')),
            ],
            options={
                'verbose_name': 'Hubungan Siswa-Wali',
                'verbose_name_plural': 'Daftar Hubungan Siswa-Wali',
                'db_table': 'guardian_links',
            },
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['foundation_id', 'person'], name='guardians_foundat_dc24df_idx'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['foundation_id', 'user'], name='guardians_foundat_1451a9_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['foundation_id', 'school_id', 'status'], name='students_foundat_a23329_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['foundation_id', 'nis'], name='students_foundat_689746_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['foundation_id', 'nisn'], name='students_foundat_dc69e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'school_id', 'nis'), name='unique_school_student_nis'),
        ),
        migrations.AddIndex(
            model_name='guardianlink',
            index=models.Index(fields=['foundation_id', 'guardian'], name='guardian_li_foundat_02888a_idx'),
        ),
        migrations.AddIndex(
            model_name='guardianlink',
            index=models.Index(fields=['foundation_id', 'student'], name='guardian_li_foundat_5c9027_idx'),
        ),
        migrations.AddIndex(
            model_name='guardianlink',
            index=models.Index(fields=['foundation_id', 'financial_responsible'], name='guardian_li_foundat_362fd7_idx'),
        ),
        migrations.AddConstraint(
            model_name='guardianlink',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'guardian', 'student'), name='unique_guardian_student_link'),
        ),
    ]
