# Generated by Django 5.2.17 on 2026-09-14 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_guardian_student_guardianlink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nip', models.CharField(blank=True, db_index=True, help_text='Nomor Induk Pegawai', max_length=32, null=True)),
                ('employment_type', models.CharField(choices=[('PERMANENT', 'Tetap (Permanent)'), ('CONTRACT', 'Kontrak (Contract)'), ('HONORARY', 'Honorer (Honorary)')], db_index=True, default='PERMANENT', max_length=32)),
                ('join_date', models.DateField(help_text='Tanggal mulai bekerja')),
                ('resignation_date', models.DateField(blank=True, help_text='Tanggal berhenti / offboarding', null=True)),
                ('resignation_reason', models.TextField(blank=True, default='', help_text='Alasan offboarding')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif (Active)'), ('ON_LEAVE', 'Cuti (On Leave)'), ('OFFBOARDED', 'Berhenti / Offboarded')], db_index=True, default='ACTIVE', max_length=32)),
                ('person', models.ForeignKey(help_text='Reference to Person PII vault (spec/02 §2)', on_delete=django.db.models.deletion.PROTECT, related_name='staff_profiles', to='identity.person')),
                ('school', models.ForeignKey(blank=True, help_text='Specific school assignment (null if foundation-wide staff)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='identity.school')),
                ('user', models.ForeignKey(help_text='Associated user account for staff system access', on_delete=django.db.models.deletion.PROTECT, related_name='staff_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staf / Pendidik',
                'verbose_name_plural': 'Daftar Staf & Pendidik',
                'db_table': 'staff',
                'indexes': [models.Index(fields=['foundation_id', 'status'], name='staff_foundat_5c5264_idx'), models.Index(fields=['foundation_id', 'school_id'], name='staff_foundat_b72755_idx'), models.Index(fields=['foundation_id', 'nip'], name='staff_foundat_2f45ec_idx')],
            },
        ),
    ]
