# Generated by Django 5.2.17 on 2026-09-16

from decimal import Decimal
import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundation',
            name='approval_threshold',
            field=apps.core.fields.MoneyField(
                decimal_places=2,
                default=Decimal('1000000.00'),
                help_text='Nominal ambang batas persetujuan yayasan untuk diskon, keringanan, dan refund (FND-007, FIN-007, FIN-032)',
                max_digits=18,
            ),
        ),
    ]
