# Generated by Django 5.2.17 on 2026-09-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_foundation_approval_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='target_grade_level',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Target entry grade level (e.g. 1, 7, 10) for prospective students', null=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['foundation_id', 'school_id', 'target_grade_level'], name='students_foundat_ab608a_idx'),
        ),
    ]
