# Generated by Django 5.2.17 on 2026-09-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_student_target_grade_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.CharField(choices=[('foundation_admin', 'Foundation Admin'), ('school_admin', 'School Admin'), ('finance_officer', 'Finance Officer'), ('teacher', 'Teacher'), ('counsellor', 'Counsellor'), ('canteen_operator', 'Canteen Operator'), ('parent', 'Parent')], db_index=True, max_length=32),
        ),
    ]
