# Generated by Django 5.1.15 on 2026-09-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_alter_roleassignment_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='nuptk',
            field=models.CharField(blank=True, db_index=True, help_text='Nomor Urut Pendidik dan Tenaga Kependidikan (DAPODIK/EMIS educator ID, CMP-017)', max_length=16, null=True),
        ),
    ]
