# Generated by Django 5.1.15 on 2026-09-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0009_staff_nuptk'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_certificate_number',
            field=models.CharField(blank=True, default='', help_text='Nomor Akta Kelahiran (DAPODIK/EMIS statutory field)', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_city',
            field=models.CharField(blank=True, default='', help_text='Tempat lahir (kota/kabupaten)', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='citizenship',
            field=models.CharField(blank=True, default='WNI', help_text='Kewarganegaraan (default WNI)', max_length=32),
        ),
        migrations.AddField(
            model_name='person',
            name='dusun',
            field=models.CharField(blank=True, default='', help_text='Dusun / Kampung', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='kabupaten_kota',
            field=models.CharField(blank=True, default='', help_text='Kabupaten / Kota', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='kecamatan',
            field=models.CharField(blank=True, default='', help_text='Kecamatan', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='kelurahan',
            field=models.CharField(blank=True, default='', help_text='Kelurahan / Desa', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='postal_code',
            field=models.CharField(blank=True, default='', help_text='Kode pos', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='provinsi',
            field=models.CharField(blank=True, default='', help_text='Provinsi', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='religion',
            field=models.CharField(blank=True, choices=[('ISLAM', 'Islam'), ('KRISTEN', 'Kristen'), ('KATOLIK', 'Katolik'), ('HINDU', 'Hindu'), ('BUDDHA', 'Buddha'), ('KONGHUCU', 'Konghucu')], default='', help_text='Agama (DAPODIK/EMIS statutory field, CMP-017)', max_length=16),
        ),
        migrations.AddField(
            model_name='person',
            name='rt',
            field=models.CharField(blank=True, default='', help_text='Rukun Tetangga', max_length=8),
        ),
        migrations.AddField(
            model_name='person',
            name='rw',
            field=models.CharField(blank=True, default='', help_text='Rukun Warga', max_length=8),
        ),
        migrations.AddField(
            model_name='school',
            name='accreditation',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('TIDAK_TERAKREDITASI', 'Belum Terakreditasi')], default='', help_text='Hasil akreditasi (A/B/C)', max_length=19),
        ),
        migrations.AddField(
            model_name='school',
            name='establishment_date',
            field=models.DateField(blank=True, help_text='Tanggal pendirian sekolah', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='kabupaten_kota',
            field=models.CharField(blank=True, default='', help_text='Kabupaten / Kota', max_length=64),
        ),
        migrations.AddField(
            model_name='school',
            name='kecamatan',
            field=models.CharField(blank=True, default='', help_text='Kecamatan', max_length=64),
        ),
        migrations.AddField(
            model_name='school',
            name='kelurahan',
            field=models.CharField(blank=True, default='', help_text='Kelurahan / Desa', max_length=64),
        ),
        migrations.AddField(
            model_name='school',
            name='nsm',
            field=models.CharField(blank=True, default='', help_text='Nomor Statistik Madrasah (EMIS, CMP-019)', max_length=16),
        ),
        migrations.AddField(
            model_name='school',
            name='nss',
            field=models.CharField(blank=True, default='', help_text='Nomor Statistik Sekolah (DAPODIK)', max_length=16),
        ),
        migrations.AddField(
            model_name='school',
            name='ownership_status',
            field=models.CharField(blank=True, choices=[('NEGERI', 'Negeri (Public)'), ('SWASTA', 'Swasta (Private)')], default='', help_text='Status kepemilikan (negeri/swasta)', max_length=16),
        ),
        migrations.AddField(
            model_name='school',
            name='postal_code',
            field=models.CharField(blank=True, default='', help_text='Kode pos', max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='provinsi',
            field=models.CharField(blank=True, default='', help_text='Provinsi', max_length=64),
        ),
        migrations.AddField(
            model_name='school',
            name='street_address',
            field=models.TextField(blank=True, default='', help_text='Alamat jalan sekolah'),
        ),
        migrations.AddField(
            model_name='staff',
            name='appointment_type',
            field=models.CharField(blank=True, choices=[('PNS', 'PNS'), ('CPNS', 'CPNS'), ('PPPK', 'PPPK'), ('GTY', 'GTY (Guru Tidak Tetap)'), ('PTT', 'PTT (Pegawai Tidak Tetap)'), ('TIDAK_ADA', 'Tidak Ada (Tetap Lokal)')], default='', help_text='Jenis pengangkatan (DAPODIK stat peg)', max_length=16),
        ),
        migrations.AddField(
            model_name='staff',
            name='certification_status',
            field=models.CharField(blank=True, choices=[('SERTIFIKAT', 'Sudah Bersertifikat Pendidik'), ('BELUM', 'Belum Bersertifikat'), ('SERTIFIKASI_PROSES', 'Sedang Proses Sertifikasi')], default='', help_text='Status sertifikasi pendidik (DAPODIK)', max_length=19),
        ),
        migrations.AddField(
            model_name='staff',
            name='degree_graduation_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Tahun lulus pendidikan terakhir', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='degree_institution',
            field=models.CharField(blank=True, default='', help_text='Institusi pendidikan terakhir', max_length=128),
        ),
        migrations.AddField(
            model_name='staff',
            name='highest_degree',
            field=models.CharField(blank=True, choices=[('SMA', 'SMA/SMK/MA'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], default='', help_text='Pendidikan tertinggi (DAPODIK)', max_length=16),
        ),
    ]
