# Generated by Django 5.1.15 on 2026-09-17 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_person_birth_certificate_number_person_birth_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider', models.CharField(choices=[('google', 'Google Workspace'), ('microsoft', 'Microsoft 365')], db_index=True, max_length=16)),
                ('provider_user_id', models.CharField(help_text="Provider's unique identifier (Google 'sub' or Microsoft 'oid')", max_length=255)),
                ('email', models.EmailField(blank=True, default='', help_text='Email used for this social login', max_length=255)),
                ('active_uniq_marker', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField())),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_logins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_logins',
                'indexes': [models.Index(fields=['foundation_id', 'user'], name='social_logi_foundat_478261_idx'), models.Index(fields=['foundation_id', 'email'], name='social_logi_foundat_51055d_idx')],
                'constraints': [models.UniqueConstraint(fields=('foundation_id', 'provider', 'provider_user_id', 'active_uniq_marker'), name='unique_active_social_login_per_provider')],
            },
        ),
    ]
