# Generated by Django 5.1.15 on 2026-09-17 08:28

import apps.identity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_step_14_1_social_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftTenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.CharField(help_text='Microsoft Entra Directory (tenant) ID — GUID atau domain terdaftar', max_length=255, validators=[apps.identity.models.validate_microsoft_tenant_id])),
                ('active_uniq_marker', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField())),
            ],
            options={
                'db_table': 'microsoft_tenant_configs',
                'indexes': [models.Index(fields=['foundation_id', 'tenant_id'], name='microsoft_t_foundat_9ad9de_idx')],
                'constraints': [models.UniqueConstraint(fields=('foundation_id', 'active_uniq_marker'), name='unique_active_ms_tenant_config_per_foundation')],
            },
        ),
    ]
