# Generated by Django 5.2.17 on 2026-09-18 02:37

import apps.core.fields
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_microsofttenantconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='home_latitude',
            field=apps.core.fields.CoordinateField(blank=True, decimal_places=6, help_text='Lintang koordinat tempat tinggal (-90 s/d +90)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90.000000')), django.core.validators.MaxValueValidator(Decimal('90.000000'))]),
        ),
        migrations.AddField(
            model_name='person',
            name='home_longitude',
            field=apps.core.fields.CoordinateField(blank=True, decimal_places=6, help_text='Bujur koordinat tempat tinggal (-180 s/d +180)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180.000000')), django.core.validators.MaxValueValidator(Decimal('180.000000'))]),
        ),
        migrations.AddField(
            model_name='person',
            name='mother_name',
            field=models.CharField(blank=True, default='', help_text='Nama ibu kandung (DAPODIK/EMIS statutory field)', max_length=128),
        ),
    ]
