# Generated by Django 5.1.15 on 2026-09-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_person_home_latitude_person_home_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.CharField(choices=[('foundation_admin', 'Foundation Admin'), ('school_admin', 'School Admin'), ('finance_officer', 'Finance Officer'), ('teacher', 'Teacher'), ('counsellor', 'Counsellor'), ('canteen_operator', 'Canteen Operator'), ('clinic_officer', 'Clinic Officer'), ('parent', 'Parent')], db_index=True, max_length=32),
        ),
    ]
