# Generated by Django 5.1.15 on 2026-09-18 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0014_alter_roleassignment_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('platform_operator', 'Platform Operator')], db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Penugasan Peran Platform',
                'verbose_name_plural': 'Daftar Penugasan Peran Platform',
                'db_table': 'platform_role_assignments',
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='unique_user_platform_role')],
            },
        ),
    ]
