# Generated by Django 5.1.15 on 2026-09-19 00:00

import apps.core.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0015_platformroleassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='qr_self_amount_max',
            field=apps.core.fields.MoneyField(decimal_places=2, default=Decimal('50000.00'), help_text='Per-charge cap for student-entered canteen QR payments (QRS-004)', max_digits=18),
        ),
    ]
