# Generated by Django 5.1.15 on 2026-09-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0017_user_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformroleassignment',
            name='role',
            field=models.CharField(choices=[('platform_operator', 'Operator Platform')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.CharField(choices=[('foundation_admin', 'Admin Yayasan'), ('school_admin', 'Admin Sekolah'), ('finance_officer', 'Bendahara'), ('teacher', 'Guru'), ('counsellor', 'Guru BK'), ('canteen_operator', 'Operator Kantin'), ('clinic_officer', 'Petugas UKS'), ('parent', 'Wali Murid')], db_index=True, max_length=32),
        ),
    ]
