# Generated by Django 5.1.15 on 2026-09-19 11:50

import apps.core.fields
from django.db import migrations, models


def seed_history_from_current_entitlements(apps, schema_editor):
    """One change per live entitlement, dated at its last update (the earliest the current value is known
    to hold). What it was before then is unknown and is read as the default, enabled."""
    Entitlement = apps.get_model('identity', 'FoundationEntitlement')
    Change = apps.get_model('identity', 'EntitlementChange')
    Change.objects.bulk_create([
        Change(
            foundation_id=e.foundation_id, school_id=e.school_id, module_key=e.module_key,
            enabled=e.enabled, effective_from=e.updated_at, created_by='migration:0019',
        )
        for e in Entitlement.objects.filter(deleted_at__isnull=True)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0018_role_choice_labels_indonesian'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitlementChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('school_id', models.BigIntegerField(blank=True, help_text='Null for the foundation-wide default', null=True)),
                ('module_key', models.CharField(choices=[('academic', 'Academic'), ('attendance', 'Attendance'), ('finance', 'Finance'), ('wallet', 'Wallet / Canteen'), ('campus_life', 'Campus Life'), ('payroll', 'Payroll'), ('analytics', 'Analytics'), ('hardware', 'Hardware & IoT')], max_length=32)),
                ('enabled', models.BooleanField(help_text="Null when the scope's own entitlement was removed", null=True)),
                ('effective_from', models.DateTimeField()),
            ],
            options={
                'db_table': 'foundation_entitlement_changes',
                'indexes': [models.Index(fields=['foundation_id', 'effective_from'], name='foundation__foundat_599796_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModulePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_tier', models.CharField(choices=[('STARTER', 'Starter'), ('STANDARD', 'Standard'), ('ENTERPRISE', 'Enterprise')], max_length=32)),
                ('module_key', models.CharField(choices=[('academic', 'Academic'), ('attendance', 'Attendance'), ('finance', 'Finance'), ('wallet', 'Wallet / Canteen'), ('campus_life', 'Campus Life'), ('payroll', 'Payroll'), ('analytics', 'Analytics'), ('hardware', 'Hardware & IoT')], max_length=32)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('unit_price', apps.core.fields.MoneyField(decimal_places=2, help_text='Per counted student per month', max_digits=18)),
                ('effective_from', models.DateField(help_text='First day of the first month this price applies to')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'module_prices',
                'constraints': [models.UniqueConstraint(fields=('plan_tier', 'module_key', 'currency', 'effective_from'), name='unique_module_price_per_start'), models.CheckConstraint(condition=models.Q(('effective_from__day', 1)), name='module_price_starts_on_first'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='module_price_not_negative')],
            },
        ),
        migrations.RunPython(seed_history_from_current_entitlements, migrations.RunPython.noop),
    ]
