# Generated by Django 5.1.15 on 2026-09-19 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0018_role_choice_labels_indonesian'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity_date',
            field=models.DateField(blank=True, help_text='Last calendar day (Asia/Jakarta) with an authenticated API request; gate for UserActivityDay.', null=True),
        ),
        migrations.CreateModel(
            name='UserActivityDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField()),
                ('active_uniq_marker', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField())),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activity_days',
                'indexes': [models.Index(fields=['foundation_id', 'date'], name='user_activi_foundat_052616_idx')],
                'constraints': [models.UniqueConstraint(fields=('foundation_id', 'user', 'date', 'active_uniq_marker'), name='unique_user_activity_day')],
            },
        ),
    ]
