# Generated by Django 5.1.15 on 2026-09-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0020_user_activity_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundation',
            name='contract_date',
            field=models.DateField(blank=True, help_text='Date the subscription contract was signed: the zero point of time-to-value (RPT-016). Set by the platform, never by the school.', null=True),
        ),
    ]
