# Generated by Django 5.2.17 on 2026-09-14 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_body', models.TextField(blank=True, default='')),
                ('response_status', models.PositiveIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'idempotency_records',
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('role', models.CharField(blank=True, default='', max_length=64)),
                ('foundation_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('school_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(db_index=True, help_text='e.g. finance.invoice.issue, academic.grade.update', max_length=128)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('diff', models.JSONField(blank=True, help_text='Before/after JSON diff with PII redacted', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_events',
                'indexes': [models.Index(fields=['foundation_id', 'timestamp'], name='audit_event_foundat_a5f7ca_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_event_entity__1d80e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('foundation_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(db_index=True, help_text='module.entity.verb format', max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'domain_events',
                'indexes': [models.Index(fields=['foundation_id', 'occurred_at'], name='domain_even_foundat_6c8a5f_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(db_index=True, max_length=128)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='RUNNING', max_length=32)),
                ('items_processed', models.PositiveIntegerField(default=0)),
                ('error_text', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'job_runs',
                'indexes': [models.Index(fields=['job_name', 'started_at'], name='job_runs_job_nam_d4763d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskQueue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('foundation_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('task_type', models.CharField(db_index=True, max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('run_after', models.DateTimeField(db_index=True, help_text='Earliest timestamp task can run')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=4)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('DEAD_LETTER', 'Dead Letter')], db_index=True, default='PENDING', max_length=32)),
                ('error_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'task_queue',
                'indexes': [models.Index(fields=['status', 'run_after'], name='task_queue_status_d43368_idx')],
            },
        ),
    ]
