# Generated by Django 5.1.15 on 2026-09-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('school_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('bucket', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=500, unique=True)),
                ('purpose', models.CharField(db_index=True, max_length=64)),
                ('content_type', models.CharField(max_length=128)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stored_files',
                'indexes': [models.Index(fields=['purpose', 'deleted_at'], name='stored_file_purpose_b65f16_idx')],
            },
        ),
    ]
