# Generated by Django 5.1.15 on 2026-09-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_storedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('report_key', models.CharField(db_index=True, help_text="Registered export-renderer key, e.g. 'foundation_dashboard'", max_length=64)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'XLSX')], max_length=16)),
                ('filters', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=32)),
                ('result_key', models.CharField(blank=True, default='', help_text='StoredFile key once COMPLETED', max_length=500)),
                ('error_text', models.TextField(blank=True, default='')),
                ('requested_by', models.CharField(blank=True, default='', max_length=64)),
                ('requested_by_name', models.CharField(blank=True, default='', help_text='Actor display name, for the RPT-003/FND-014 export header', max_length=128)),
            ],
            options={
                'db_table': 'export_jobs',
                'indexes': [models.Index(fields=['foundation_id', 'status'], name='export_jobs_foundat_d105d7_idx')],
            },
        ),
    ]
