# Generated by Django 5.1.15 on 2026-09-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exportjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='format',
            field=models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'XLSX'), ('CSV', 'CSV')], max_length=16),
        ),
    ]
