# Generated by Django 5.1.15 on 2026-09-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_exportjob_format'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['foundation_id', 'action'], name='audit_event_foundat_751cce_idx'),
        ),
    ]
