# Generated by Django 5.1.15 on 2026-09-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditevent_audit_event_foundat_751cce_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event_name', models.CharField(choices=[('app_open', 'app_open'), ('child_switch', 'child_switch'), ('invoice_view', 'invoice_view'), ('pay_start', 'pay_start'), ('pay_method_selected', 'pay_method_selected'), ('pay_intent_created', 'pay_intent_created'), ('pay_completed', 'pay_completed'), ('topup_completed', 'topup_completed'), ('absence_submitted', 'absence_submitted'), ('grades_view', 'grades_view'), ('report_card_view', 'report_card_view'), ('notification_opened', 'notification_opened')], db_index=True, max_length=32)),
                ('school_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(max_length=32)),
                ('occurred_at', models.DateTimeField(help_text='Client-reported event time; may differ from created_at for offline-queued events')),
            ],
            options={
                'db_table': 'analytics_events',
                'indexes': [models.Index(fields=['foundation_id', 'event_name', 'occurred_at'], name='analytics_e_foundat_7a272f_idx'), models.Index(fields=['foundation_id', 'occurred_at'], name='analytics_e_foundat_b3e578_idx')],
            },
        ),
    ]
