# Generated by Django 5.1.15 on 2026-09-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_analyticsevent'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['foundation_id', 'purpose'], name='idx_storedfile_fnd_purpose'),
        ),
    ]
