# Generated by Django 5.1.15 on 2026-09-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tenant_foundation_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEventArchive',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('actor_id', models.CharField(blank=True, max_length=64, null=True)),
                ('role', models.CharField(blank=True, default='', max_length=64)),
                ('foundation_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('school_id', models.BigIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(help_text='e.g. finance.invoice.issue, academic.grade.update', max_length=128)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('diff', models.JSONField(blank=True, help_text='Before/after JSON diff with PII redacted', null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'audit_events_archive',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DomainEventArchive',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('foundation_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(help_text='module.entity.verb format', max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'domain_events_archive',
                'default_permissions': (),
            },
        ),
    ]
