# Generated by Django 5.1.15 on 2026-09-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatutoryExportSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('system', models.CharField(choices=[('DAPODIK', 'DAPODIK (Kemendikbudristek)'), ('EMIS', 'EMIS (Kemenag Madrasah)')], db_index=True, help_text='Which ministry reporting system this schema targets', max_length=16)),
                ('version', models.CharField(help_text="Statutory schema version label, e.g. '2026.1' — data, not code (CMP-020)", max_length=32)),
                ('is_active', models.BooleanField(default=True, help_text='Only the active schema version is used for new exports')),
                ('field_map', models.JSONField(default=dict, help_text='Entity sheet -> {EduCore field path -> statutory column name}. Entity sheets: students, staff, rombel.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'statutory_export_schemas',
                'indexes': [models.Index(fields=['foundation_id', 'system', 'is_active'], name='statutory_e_foundat_40f789_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'system', 'version'), name='unique_active_statutory_schema_per_foundation_system_version')],
            },
        ),
    ]
