# Generated by Django 5.2.17 on 2026-09-18 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('core', '0006_analyticsevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiiExportAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('report_key', models.CharField(db_index=True, help_text="Registered report key, e.g. 'statutory_dapodik', 'statutory_emis'", max_length=64)),
                ('format', models.CharField(help_text='Export format (e.g. XLSX, CSV)', max_length=16)),
                ('exported_by_id', models.CharField(db_index=True, help_text='User ID of the requesting actor', max_length=64)),
                ('exported_by_name', models.CharField(blank=True, default='', help_text='Full name of the requesting actor', max_length=128)),
                ('school_id', models.IntegerField(blank=True, db_index=True, help_text='Target school ID if the export was school-scoped', null=True)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Filters applied to the export query')),
                ('record_count', models.IntegerField(default=0, help_text='Number of records/rows exported')),
                ('watermark_text', models.TextField(blank=True, default='', help_text='Visible watermark text stamped on the document')),
                ('file_name', models.CharField(blank=True, default='', help_text='Generated filename', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times download link was accessed')),
                ('last_downloaded_at', models.DateTimeField(blank=True, help_text='Last time the download link was retrieved', null=True)),
                ('export_job', models.ForeignKey(blank=True, help_text='Associated async export job if generated via ExportJob pipeline', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pii_access_logs', to='core.exportjob')),
            ],
            options={
                'db_table': 'pii_export_access_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['foundation_id', '-created_at'], name='pii_export__foundat_b93ec6_idx'), models.Index(fields=['foundation_id', 'report_key', '-created_at'], name='pii_export__foundat_697c1e_idx'), models.Index(fields=['foundation_id', 'exported_by_id', '-created_at'], name='pii_export__foundat_d33bd6_idx')],
            },
        ),
    ]
