# Generated by Django 5.1.15 on 2026-09-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_piiexportaccesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('subject_type', models.CharField(choices=[('STUDENT', 'Siswa'), ('STAFF', 'Staf')], db_index=True, max_length=16)),
                ('subject_id', models.BigIntegerField(help_text="Student.id or Staff.id — a plain integer, not an FK, so this row survives the subject's Person row being anonymized.")),
                ('status', models.CharField(choices=[('COMPLETED', 'Selesai'), ('REFUSED', 'Ditolak')], db_index=True, max_length=16)),
                ('requested_by', models.CharField(blank=True, default='', max_length=64)),
                ('requested_by_name', models.CharField(blank=True, default='', max_length=128)),
                ('refusal_reason', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'data_subject_erasure_requests',
                'indexes': [models.Index(fields=['foundation_id', 'subject_type', 'subject_id'], name='data_subjec_foundat_53a112_idx'), models.Index(fields=['foundation_id', 'status'], name='data_subjec_foundat_ae1412_idx')],
            },
        ),
    ]
