# Generated by Django 5.2.17 on 2026-09-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_piiexportaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='statutoryexportschema',
            name='mandatory_fields',
            field=models.JSONField(blank=True, default=dict, help_text="Optional mandatory field paths per entity sheet for pre-export validation (CMP-018, CMP-020). E.g., {'students': ['person.mother_name', 'person.home_latitude', 'person.home_longitude']}"),
        ),
    ]
