# Generated by Django 5.1.15 on 2026-09-18 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_datasubjectrequest'),
        ('compliance', '0003_statutoryexportschema_mandatory_fields'),
    ]

    operations = [
    ]
