# Generated by Django 5.1.15 on 2026-09-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_merge_20260918_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('subject_type', models.CharField(choices=[('STUDENT', 'Siswa'), ('STAFF', 'Staf')], db_index=True, max_length=16)),
                ('subject_id', models.BigIntegerField(help_text='Student.id or Staff.id')),
                ('purpose', models.CharField(choices=[('BIOMETRIC', 'Pendaftaran Biometrik'), ('PHOTO_MEDIA', 'Penggunaan Foto/Media'), ('HEALTH_DATA', 'Pemrosesan Data Kesehatan'), ('MARKETING', 'Komunikasi Pemasaran')], db_index=True, max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('granted_at', models.DateTimeField()),
                ('granted_by', models.CharField(blank=True, default='', help_text='User ID of the guardian/admin who recorded the grant', max_length=64)),
                ('withdrawn_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('withdrawn_by', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'consent_records',
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['foundation_id', 'subject_type', 'subject_id', 'purpose'], name='consent_rec_foundat_df8a8b_idx'), models.Index(fields=['foundation_id', 'purpose', 'withdrawn_at'], name='consent_rec_foundat_3523fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('foundation_id', 'subject_type', 'subject_id', 'purpose', 'version'), name='unique_consent_version_per_subject_purpose')],
            },
        ),
    ]
