# Generated by Django 5.1.15 on 2026-09-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_consentrecord'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='statutoryexportschema',
            name='unique_active_statutory_schema_per_foundation_system_version',
        ),
        migrations.AddField(
            model_name='statutoryexportschema',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddConstraint(
            model_name='statutoryexportschema',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'system', 'version', 'active_uniq_marker'), name='unique_active_statutory_schema_per_foundation_system_version'),
        ),
    ]
