# Generated by Django 5.1.15 on 2026-09-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name_id', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128)),
                ('note_id', models.CharField(blank=True, default='', max_length=255)),
                ('note_en', models.CharField(blank=True, default='', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('manual_status', models.CharField(blank=True, choices=[('OPERATIONAL', 'Operational'), ('DEGRADED', 'Degraded'), ('DOWN', 'Down')], help_text='Staff override. Null means derive status from the daily heartbeat rollup.', max_length=16, null=True)),
            ],
            options={
                'verbose_name': 'Komponen Layanan',
                'verbose_name_plural': 'Daftar Komponen Layanan',
                'db_table': 'status_components',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
