# Generated by Django 5.1.15 on 2026-09-18 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_seed_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(db_index=True)),
                ('is_up', models.BooleanField()),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='status.servicecomponent')),
            ],
            options={
                'verbose_name': 'Denyut Nadi Komponen',
                'verbose_name_plural': 'Daftar Denyut Nadi Komponen',
                'db_table': 'status_component_heartbeats',
                'indexes': [models.Index(fields=['component', 'checked_at'], name='status_comp_compone_baee8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyComponentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('DEGRADED', 'Degraded'), ('DOWN', 'Down')], max_length=16)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_statuses', to='status.servicecomponent')),
            ],
            options={
                'verbose_name': 'Status Harian Komponen',
                'verbose_name_plural': 'Daftar Status Harian Komponen',
                'db_table': 'status_daily_component_status',
                'indexes': [models.Index(fields=['date'], name='status_dail_date_f89f63_idx')],
                'constraints': [models.UniqueConstraint(fields=('component', 'date'), name='unique_component_date')],
            },
        ),
    ]
