# Generated by Django 5.1.15 on 2026-09-18 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_componentheartbeat_dailycomponentstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major'), ('MAINTENANCE', 'Maintenance')], max_length=16)),
                ('title_id', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('body_id', models.TextField()),
                ('body_en', models.TextField()),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_components', models.ManyToManyField(blank=True, related_name='incidents', to='status.servicecomponent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insiden Status',
                'verbose_name_plural': 'Daftar Insiden Status',
                'db_table': 'status_incidents',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
