# Generated by Django 5.1.15 on 2026-09-18 11:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_statusincident'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Pelanggan Pembaruan Status',
                'verbose_name_plural': 'Daftar Pelanggan Pembaruan Status',
                'db_table': 'status_subscribers',
            },
        ),
    ]
