# Generated by Django 5.1.15 on 2026-09-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_fix_notifications_seed_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycomponentstatus',
            name='date',
            field=models.DateField(),
        ),
    ]
