# Generated by Django 5.1.15 on 2026-09-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0007_alter_dailycomponentstatus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentheartbeat',
            name='status',
            field=models.CharField(blank=True, choices=[('OPERATIONAL', 'Operational'), ('DEGRADED', 'Degraded'), ('DOWN', 'Down')], help_text='Full OPERATIONAL/DEGRADED/DOWN probe signal. Null on pre-migration rows — read as DOWN if is_up=False else OPERATIONAL for backward compatibility.', max_length=16, null=True),
        ),
    ]
