# Generated by Django 5.2.17 on 2026-09-14 15:07

import apps.core.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RptFoundationKPI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('foundation_id', models.BigIntegerField(db_index=True)),
                ('school_id', models.BigIntegerField(blank=True, db_index=True, help_text='Null for foundation-wide aggregate', null=True)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('billed', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount billed in period', max_digits=18)),
                ('collected', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount collected in period', max_digits=18)),
                ('outstanding', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Total outstanding AR', max_digits=18)),
                ('ar_0_30', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='AR aging bucket 0-30 days', max_digits=18)),
                ('ar_31_60', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='AR aging bucket 31-60 days', max_digits=18)),
                ('ar_61_90', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='AR aging bucket 61-90 days', max_digits=18)),
                ('ar_90_plus', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='AR aging bucket 90+ days', max_digits=18)),
                ('campus_spend', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Cashless canteen/store spend', max_digits=18)),
                ('active_students', models.PositiveIntegerField(default=0)),
                ('avg_attendance_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('reporting_currency', models.CharField(default='IDR', max_length=3)),
                ('fx_rate_date', models.DateField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rollup KPI Yayasan',
                'verbose_name_plural': 'Daftar Rollup KPI Yayasan',
                'db_table': 'rpt_foundation_kpis',
                'indexes': [models.Index(fields=['foundation_id', 'period_start', 'period_end'], name='rpt_foundat_foundat_f18803_idx'), models.Index(fields=['foundation_id', 'school_id'], name='rpt_foundat_foundat_161b06_idx')],
            },
        ),
    ]
