# Generated by Django 5.1.15 on 2026-09-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rptfoundationkpi',
            name='multi_currency_status',
            field=models.CharField(choices=[('SINGLE_CURRENCY', 'Single Currency'), ('CONSOLIDATED', 'Consolidated'), ('MIXED_CURRENCY_UNSUPPORTED', 'Mixed Currency Unsupported')], default='SINGLE_CURRENCY', help_text='Consolidation status for multi-currency foundations (FND-005b)', max_length=32),
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('base_currency', models.CharField(help_text='Source currency (e.g. USD)', max_length=3)),
                ('quote_currency', models.CharField(help_text='Target currency (e.g. IDR)', max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, help_text='Conversion rate: 1 base_currency = rate quote_currency (CUR-021)', max_digits=18)),
                ('effective_date', models.DateField(help_text='Date this rate is effective from')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORTED', 'Imported')], default='MANUAL', max_length=16)),
                ('active_uniq_marker', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField())),
            ],
            options={
                'verbose_name': 'Nilai Tukar',
                'verbose_name_plural': 'Daftar Nilai Tukar',
                'db_table': 'fx_rates',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['foundation_id', 'base_currency', 'quote_currency', 'effective_date'], name='fx_rates_foundat_6b2c68_idx')],
                'constraints': [models.UniqueConstraint(fields=('foundation_id', 'base_currency', 'quote_currency', 'effective_date', 'active_uniq_marker'), name='unique_fx_rate_per_foundation_currency_date')],
            },
        ),
    ]
