# Generated by Django 5.2.17 on 2026-09-15 23:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0010_reportcard_extracurricular_notes_and_more'),
        ('identity', '0005_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviourCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trigger', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Terbuka'), ('IN_PROGRESS', 'Dalam Penanganan'), ('RESOLVED', 'Terselesaikan'), ('CLOSED', 'Ditutup')], default='OPEN', max_length=20)),
                ('resolution', models.TextField(blank=True, default='')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_counsellor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_behaviour_cases', to='identity.staff')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_cases', to='identity.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_cases', to='identity.student')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behaviour_cases', to='academic.term')),
            ],
            options={
                'db_table': 'campus_behaviour_cases',
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BehaviourPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('escalation_negative_threshold', models.IntegerField(default=-25, help_text='Ambang batas akumulasi poin negatif per semester untuk auto-buka behaviour case (LIF-009).')),
                ('rapor_includes_behaviour', models.BooleanField(default=False, help_text='Apakah ringkasan poin perilaku dicantumkan di buku rapor (LIF-014).')),
                ('default_counsellor', models.ForeignKey(blank=True, help_text='Konselor BK default yang ditugaskan saat threshold terlampaui.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselor_behaviour_policies', to='identity.staff')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_policy', to='identity.school')),
            ],
            options={
                'verbose_name': 'Kebijakan Perilaku Sekolah',
                'verbose_name_plural': 'Kebijakan Perilaku Sekolah',
                'db_table': 'campus_behaviour_policies',
            },
        ),
        migrations.CreateModel(
            name='BehaviourReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('points', models.IntegerField(help_text='Nilai poin (positif untuk kebaikan, negatif untuk pelanggaran).')),
                ('category', models.CharField(choices=[('POSITIVE', 'Positif'), ('MINOR', 'Pelanggaran Ringan'), ('MAJOR', 'Pelanggaran Berat')], default='MINOR', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_reasons', to='identity.school')),
            ],
            options={
                'db_table': 'campus_behaviour_reasons',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BehaviourRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('points', models.IntegerField(help_text='Snapshot nilai poin yang diterapkan.')),
                ('note', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_by_guardian_at', models.DateTimeField(blank=True, null=True)),
                ('is_superseded', models.BooleanField(default=False)),
                ('correction_reason', models.TextField(blank=True, default='')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_behaviour_records', to='identity.guardian')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='campus.behaviourreason')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_behaviour_records', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_records', to='identity.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_records', to='identity.student')),
                ('superseded_by', models.OneToOneField(blank=True, help_text='Rekaman pengganti jika catatan ini dikoreksi (LIF-013).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes_record', to='campus.behaviourrecord')),
                ('term', models.ForeignKey(blank=True, help_text='Semester akademik saat kejadian (LIF-008).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behaviour_records', to='academic.term')),
            ],
            options={
                'db_table': 'campus_behaviour_records',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='behaviourreason',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'school', 'code'), name='unique_school_behaviour_reason_code'),
        ),
    ]
