# Generated by Django 5.1.15 on 2026-09-18 04:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('identity', '0013_person_home_latitude_person_home_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('BOOK', 'Buku'), ('EBOOK', 'E-Buku'), ('EQUIPMENT', 'Peralatan')], db_index=True, default='BOOK', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('isbn', models.CharField(blank=True, default='', max_length=32)),
                ('copies_total', models.PositiveIntegerField(default=1)),
                ('copies_available', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(blank=True, default='', max_length=128)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='identity.school')),
            ],
            options={
                'verbose_name': 'Item Perpustakaan',
                'verbose_name_plural': 'Item Perpustakaan',
                'db_table': 'campus_library_items',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('borrower_type', models.CharField(choices=[('STUDENT', 'Siswa'), ('STAFF', 'Staf')], db_index=True, max_length=16)),
                ('borrower_id', models.BigIntegerField(help_text='Student.id or Staff.id')),
                ('borrowed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('fine', models.PositiveIntegerField(default=0, help_text='Reserved for LIF-020; not computed in this slice.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Dipinjam'), ('RETURNED', 'Dikembalikan'), ('OVERDUE', 'Terlambat')], db_index=True, default='ACTIVE', max_length=16)),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='campus.libraryitem')),
            ],
            options={
                'verbose_name': 'Peminjaman Perpustakaan',
                'verbose_name_plural': 'Peminjaman Perpustakaan',
                'db_table': 'campus_library_loans',
                'ordering': ['-borrowed_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='libraryitem',
            index=models.Index(fields=['foundation_id', 'school', 'type'], name='idx_libitem_fnd_sch_type'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['foundation_id', 'status', 'due_at'], name='idx_loan_fnd_st_due'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['foundation_id', 'borrower_type', 'borrower_id'], name='idx_loan_fnd_borrower'),
        ),
    ]
