# Generated by Django 5.1.15 on 2026-09-18 04:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_libraryitem_loan_and_more'),
        ('identity', '0013_person_home_latitude_person_home_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('INITIAL', 'Sesi Awal'), ('FOLLOW_UP', 'Sesi Lanjutan'), ('MEDIATION', 'Mediasi'), ('PARENT_MEETING', 'Pertemuan Orang Tua'), ('OTHER', 'Lainnya')], default='INITIAL', max_length=20)),
                ('notes_encrypted', models.TextField(blank=True, default='', help_text='Catatan sesi, terenkripsi at-rest (LIF-015).')),
                ('follow_up_at', models.DateTimeField(blank=True, help_text='Tanggal tindak lanjut; memicu pengingat tugas konselor (LIF-018).', null=True)),
                ('confidentiality', models.CharField(choices=[('NORMAL', 'Normal'), ('RESTRICTED', 'Terbatas (Restricted)')], default='NORMAL', help_text='RESTRICTED hanya terlihat oleh konselor penulis dan kepala sekolah (LIF-015).', max_length=20)),
                ('is_urgent', models.BooleanField(default=False, help_text='Eskalasi perlindungan anak (safeguarding) — memberitahu kepala sekolah langsung (LIF-017).')),
                ('urgent_notified_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_reminder_sent_at', models.DateTimeField(blank=True, help_text='Kapan pengingat tugas tindak lanjut dikirim ke konselor (LIF-018).', null=True)),
                ('case', models.ForeignKey(blank=True, help_text='Kasus perilaku terkait (opsional) — sesi BK dapat berdiri sendiri.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselling_sessions', to='campus.behaviourcase')),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counselling_sessions', to='identity.staff')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_sessions', to='identity.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_sessions', to='identity.student')),
            ],
            options={
                'db_table': 'campus_counselling_sessions',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['foundation_id', 'follow_up_at'], name='campus_coun_foundat_94b35b_idx')],
            },
        ),
    ]
