# Generated by Django 5.1.15 on 2026-09-18 04:26

import apps.core.fields
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_counsellingsession'),
        ('identity', '0013_person_home_latitude_person_home_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='replacement_cost',
            field=apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Biaya penggantian jika hilang (LIF-021).', max_digits=18),
        ),
        migrations.AddField(
            model_name='loan',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_library_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='condition_on_issue',
            field=models.CharField(blank=True, default='', help_text='Kondisi barang saat dipinjamkan, wajib untuk EQUIPMENT (LIF-022).', max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='condition_on_return',
            field=models.CharField(blank=True, default='', help_text='Kondisi barang saat dikembalikan, wajib untuk EQUIPMENT (LIF-022).', max_length=255),
        ),
        migrations.AlterField(
            model_name='loan',
            name='fine',
            field=apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Denda keterlambatan, dihitung saat pengembalian (LIF-020).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Dipinjam'), ('RETURNED', 'Dikembalikan'), ('OVERDUE', 'Terlambat'), ('LOST', 'Hilang')], db_index=True, default='ACTIVE', max_length=16),
        ),
        migrations.CreateModel(
            name='LibraryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('borrower_type', models.CharField(choices=[('STUDENT', 'Siswa'), ('STAFF', 'Staf')], max_length=16)),
                ('loan_period_days', models.PositiveIntegerField(default=7, help_text='Lama masa pinjam dalam hari (LIF-019).')),
                ('max_concurrent_loans', models.PositiveIntegerField(default=3, help_text='Jumlah maksimum pinjaman aktif bersamaan (LIF-019).')),
                ('fine_per_day', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Denda keterlambatan per hari (LIF-020).', max_digits=18)),
                ('fine_cap', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Batas maksimum denda keterlambatan (LIF-020).', max_digits=18)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_policies', to='identity.school')),
            ],
            options={
                'db_table': 'campus_library_policies',
                'abstract': False,
                'indexes': [models.Index(fields=['foundation_id', 'deleted_at'], name='campus_libr_foundat_2c37a4_idx')],
                'constraints': [models.UniqueConstraint(fields=('foundation_id', 'school', 'borrower_type'), name='unique_school_library_policy_borrower_type')],
            },
        ),
    ]
