# Generated by Django 5.1.15 on 2026-09-18 04:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_libraryitem_replacement_cost_loan_checked_out_by_and_more'),
        ('identity', '0014_alter_roleassignment_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('teacher_sees_allergies', models.BooleanField(default=True, help_text='LIF-006: guru dapat melihat daftar alergi siswa pada ringkasan non-klinis (default aktif karena keselamatan).')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_policy', to='identity.school')),
            ],
            options={
                'verbose_name': 'Kebijakan Klinik Sekolah',
                'verbose_name_plural': 'Kebijakan Klinik Sekolah',
                'db_table': 'campus_clinic_policies',
            },
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('blood_type', models.CharField(blank=True, default='', max_length=8)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('chronic_conditions', models.JSONField(blank=True, default=list)),
                ('medications', models.JSONField(blank=True, default=list)),
                ('emergency_contacts', models.JSONField(blank=True, default=dict)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to='identity.student')),
            ],
            options={
                'verbose_name': 'Profil Kesehatan Siswa',
                'verbose_name_plural': 'Profil Kesehatan Siswa',
                'db_table': 'campus_health_profiles',
            },
        ),
        migrations.CreateModel(
            name='MedicationStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=32)),
                ('quantity', models.IntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('reorder_level', models.IntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_stocks', to='identity.school')),
            ],
            options={
                'db_table': 'campus_medication_stock',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('complaint_encrypted', models.TextField(help_text='LIF-007: keluhan terenkripsi Fernet, lihat apps.campus.crypto.')),
                ('treatment_encrypted', models.TextField(blank=True, default='', help_text='LIF-007: penanganan terenkripsi Fernet, lihat apps.campus.crypto.')),
                ('vitals', models.JSONField(blank=True, default=dict)),
                ('medication_quantity_used', models.IntegerField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('RETURNED_TO_CLASS', 'Kembali ke Kelas'), ('SENT_HOME', 'Dipulangkan'), ('REFERRED', 'Dirujuk')], max_length=20)),
                ('guardian_consent_confirmed', models.BooleanField(default=False)),
                ('guardian_consent_note', models.CharField(blank=True, default='', max_length=255)),
                ('guardian_notified_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handled_clinic_visits', to='identity.staff')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_visits', to='identity.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_visits', to='identity.student')),
                ('medication_given', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_visits', to='campus.medicationstock')),
            ],
            options={
                'db_table': 'campus_clinic_visits',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['foundation_id', 'school_id', 'occurred_at'], name='campus_clin_foundat_608880_idx'), models.Index(fields=['foundation_id', 'student_id', 'occurred_at'], name='campus_clin_foundat_acf034_idx')],
            },
        ),
    ]
