# Generated by Django 5.1.15 on 2026-09-19 04:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_academiccalendarevent_calendaracademicsyncpolicy'),
        ('campus', '0005_clinicpolicy_healthprofile_medicationstock_and_more'),
        ('identity', '0017_user_pin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='behaviourcase',
            index=models.Index(fields=['foundation_id', 'student', 'status'], name='idx_behcase_fnd_stu_st'),
        ),
        migrations.AddIndex(
            model_name='behaviourrecord',
            index=models.Index(fields=['foundation_id', 'student', 'occurred_at'], name='idx_behrec_fnd_stu_occ'),
        ),
        migrations.AddIndex(
            model_name='medicationstock',
            index=models.Index(fields=['foundation_id', 'school', 'expiry_date'], name='idx_medstock_fnd_sch_exp'),
        ),
    ]
