# Generated by Django 5.1.15 on 2026-09-15 01:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0005_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('FORMATIVE', 'Formatif'), ('SUMMATIVE', 'Sumatif'), ('PROJECT', 'Proyek'), ('PRACTICAL', 'Praktik'), ('EXAM', 'Ujian')], max_length=16)),
                ('title', models.CharField(max_length=128)),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage weight toward the final term grade, for weighted types only', max_digits=5)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'assessments',
            },
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('grade_level', models.PositiveSmallIntegerField()),
                ('code', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'learning_objectives',
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='e.g. 2026/2027', max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_years', to='identity.school')),
            ],
            options={
                'db_table': 'academic_years',
            },
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('descriptor', models.CharField(blank=True, default='', max_length=32)),
                ('feedback', models.TextField(blank=True, default='')),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='academic.assessment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_scores', to='identity.student')),
            ],
            options={
                'db_table': 'assessment_scores',
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('grade_level', models.PositiveSmallIntegerField(help_text='Numeric grade level, e.g. 10')),
                ('name', models.CharField(help_text='e.g. X IPA 1', max_length=64)),
                ('capacity', models.PositiveSmallIntegerField(default=36)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='academic.academicyear')),
                ('homeroom_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_class_groups', to='identity.staff')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='identity.school')),
            ],
            options={
                'db_table': 'class_groups',
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('enrolled_at', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_enrollments', to='identity.student')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academic.classgroup')),
            ],
            options={
                'db_table': 'class_enrollments',
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_subjects', to='academic.classgroup')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='identity.staff')),
            ],
            options={
                'db_table': 'class_subjects',
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='class_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academic.classsubject'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='objectives',
            field=models.ManyToManyField(blank=True, related_name='assessments', to='academic.learningobjective'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('level', models.CharField(blank=True, default='', help_text='School level this subject applies to, e.g. SMA', max_length=16)),
                ('is_religious', models.BooleanField(default=False)),
                ('credit_hours', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='identity.school')),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.AddField(
            model_name='learningobjective',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_objectives', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_subjects', to='academic.subject'),
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='e.g. Semester 1 (Ganjil)', max_length=64)),
                ('term_no', models.PositiveSmallIntegerField(help_text='1 or 2')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='academic.academicyear')),
            ],
            options={
                'db_table': 'terms',
            },
        ),
        migrations.AddField(
            model_name='classsubject',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_subjects', to='academic.term'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['foundation_id', 'school_id', 'is_active'], name='academic_ye_foundat_9e99a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'school', 'name'), name='unique_academic_year_name_per_school'),
        ),
        migrations.AddIndex(
            model_name='assessmentscore',
            index=models.Index(fields=['foundation_id', 'assessment_id'], name='assessment__foundat_317bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentscore',
            index=models.Index(fields=['foundation_id', 'student_id'], name='assessment__foundat_3df9bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentscore',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'assessment', 'student'), name='unique_score_per_assessment_student'),
        ),
        migrations.AddIndex(
            model_name='classgroup',
            index=models.Index(fields=['foundation_id', 'school_id', 'academic_year_id'], name='class_group_foundat_770e6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='classgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'academic_year', 'name'), name='unique_class_group_name_per_academic_year'),
        ),
        migrations.AddIndex(
            model_name='classenrollment',
            index=models.Index(fields=['foundation_id', 'class_group_id', 'is_active'], name='class_enrol_foundat_814bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='classenrollment',
            index=models.Index(fields=['foundation_id', 'student_id', 'is_active'], name='class_enrol_foundat_b94d4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='classenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'student', 'class_group'), name='unique_active_enrollment_per_student_class_group'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['foundation_id', 'class_subject_id', 'type'], name='assessments_foundat_9d60ee_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['foundation_id', 'class_subject_id', 'published'], name='assessments_foundat_ad0e37_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['foundation_id', 'school_id', 'is_active'], name='subjects_foundat_dce3bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'school', 'code'), name='unique_subject_code_per_school'),
        ),
        migrations.AddIndex(
            model_name='learningobjective',
            index=models.Index(fields=['foundation_id', 'subject_id', 'grade_level'], name='learning_ob_foundat_7defc2_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningobjective',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'subject', 'code'), name='unique_objective_code_per_subject'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['foundation_id', 'academic_year_id'], name='terms_foundat_f7b06c_idx'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'academic_year', 'term_no'), name='unique_term_no_per_academic_year'),
        ),
        migrations.AddIndex(
            model_name='classsubject',
            index=models.Index(fields=['foundation_id', 'class_group_id', 'term_id'], name='class_subje_foundat_9600ad_idx'),
        ),
        migrations.AddIndex(
            model_name='classsubject',
            index=models.Index(fields=['foundation_id', 'teacher_id'], name='class_subje_foundat_313521_idx'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'class_group', 'subject', 'term'), name='unique_class_subject_per_term'),
        ),
    ]
