# Generated by Django 5.1.15 on 2026-09-15 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('identity', '0005_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, 'Jumat'), (6, 'Sabtu'), (7, 'Minggu')])),
                ('period_no', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, default='', max_length=64)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='academic.classsubject')),
            ],
            options={
                'db_table': 'timetable_slots',
            },
        ),
        migrations.CreateModel(
            name='TimetableSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('original_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.staff')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitutions', to='academic.timetableslot')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitute_assignments', to='identity.staff')),
            ],
            options={
                'db_table': 'timetable_substitutions',
            },
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['foundation_id', 'class_subject_id', 'day_of_week'], name='timetable_s_foundat_b92f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['foundation_id', 'day_of_week', 'period_no'], name='timetable_s_foundat_3a971d_idx'),
        ),
        migrations.AddIndex(
            model_name='timetablesubstitution',
            index=models.Index(fields=['foundation_id', 'slot_id', 'date'], name='timetable_s_foundat_e7928d_idx'),
        ),
        migrations.AddIndex(
            model_name='timetablesubstitution',
            index=models.Index(fields=['foundation_id', 'substitute_teacher_id', 'date'], name='timetable_s_foundat_773914_idx'),
        ),
        migrations.AddConstraint(
            model_name='timetablesubstitution',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'slot', 'date'), name='unique_substitution_per_slot_date'),
        ),
    ]
