# Generated by Django 5.1.15 on 2026-09-15 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_timetableslot_timetablesubstitution_and_more'),
        ('identity', '0005_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=128)),
                ('instructions', models.TextField(blank=True, default='')),
                ('assigned_at', models.DateTimeField()),
                ('due_at', models.DateTimeField()),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_assignments', to='academic.classsubject')),
            ],
            options={
                'db_table': 'homework',
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('submitted_at', models.DateTimeField()),
                ('files', models.JSONField(blank=True, default=list, help_text='List of {key, filename, size, content_type}')),
                ('text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Terkumpul'), ('LATE', 'Terlambat'), ('GRADED', 'Dinilai'), ('RETURNED', 'Dikembalikan')], max_length=16)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True, default='')),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='academic.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_submissions', to='identity.student')),
            ],
            options={
                'db_table': 'homework_submissions',
            },
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['foundation_id', 'class_subject_id', 'due_at'], name='homework_foundat_017b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['foundation_id', 'homework_id', 'status'], name='homework_su_foundat_b23483_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['foundation_id', 'student_id'], name='homework_su_foundat_230d03_idx'),
        ),
        migrations.AddConstraint(
            model_name='homeworksubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'homework', 'student'), name='unique_submission_per_homework_student'),
        ),
    ]
