# Generated by Django 5.1.15 on 2026-09-15 02:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_homework_homeworksubmission_and_more'),
        ('identity', '0005_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=128)),
                ('mode', models.CharField(choices=[('ONLINE', 'Daring'), ('PAPER', 'Kertas')], default='ONLINE', max_length=16)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('duration_min', models.PositiveSmallIntegerField()),
                ('shuffle', models.BooleanField(default=False)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='one_question_at_a_time, block_back_navigation, full_screen_lock, etc.')),
                ('published', models.BooleanField(default=False)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academic.classsubject')),
            ],
            options={
                'db_table': 'exams',
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('auto_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('manual_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Sedang Berjalan'), ('SUBMITTED', 'Terkumpul'), ('AUTO_SUBMITTED', 'Terkumpul Otomatis')], default='IN_PROGRESS', max_length=16)),
                ('question_order', models.JSONField(blank=True, default=list, help_text='Per-attempt shuffled question id order (ACD-024)')),
                ('focus_loss_count', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='academic.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_attempts', to='identity.student')),
            ],
            options={
                'db_table': 'exam_attempts',
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('seq', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('MCQ', 'Pilihan Ganda'), ('MULTI', 'Pilihan Ganda Kompleks'), ('TRUE_FALSE', 'Benar/Salah'), ('SHORT', 'Jawaban Singkat'), ('ESSAY', 'Esai'), ('MATCHING', 'Menjodohkan')], max_length=16)),
                ('body', models.TextField()),
                ('media', models.JSONField(blank=True, default=list)),
                ('options', models.JSONField(blank=True, default=list, help_text='Choice list for MCQ/MULTI/MATCHING, e.g. [{key, text}]')),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('answer_key', models.JSONField(blank=True, default=dict, help_text='Grading key; shape depends on type')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='academic.exam')),
            ],
            options={
                'db_table': 'exam_questions',
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('answer', models.JSONField(blank=True, default=dict)),
                ('points_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='academic.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academic.examquestion')),
            ],
            options={
                'db_table': 'exam_answers',
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['foundation_id', 'class_subject_id'], name='exams_foundat_9beeb1_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['foundation_id', 'exam_id', 'student_id'], name='exam_attemp_foundat_86891f_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['foundation_id', 'status'], name='exam_attemp_foundat_6a8f9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'exam', 'student'), name='unique_attempt_per_exam_student'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['foundation_id', 'exam_id', 'seq'], name='exam_questi_foundat_9bb3ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'exam', 'seq'), name='unique_question_seq_per_exam'),
        ),
        migrations.AddIndex(
            model_name='examanswer',
            index=models.Index(fields=['foundation_id', 'attempt_id'], name='exam_answer_foundat_89c807_idx'),
        ),
        migrations.AddConstraint(
            model_name='examanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'attempt', 'question'), name='unique_answer_per_attempt_question'),
        ),
    ]
