# Generated by Django 5.1.15 on 2026-09-15 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_exam_examattempt_examquestion_examanswer_and_more'),
        ('identity', '0005_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCardPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('block_rapor_on_arrears', models.BooleanField(default=False)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report_card_policy', to='identity.school')),
            ],
            options={
                'db_table': 'report_card_policies',
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Konsep'), ('PENDING_REVIEW', 'Menunggu Tinjauan'), ('APPROVED', 'Disetujui'), ('PUBLISHED', 'Diterbitkan')], default='DRAFT', max_length=16)),
                ('grades_snapshot', models.JSONField(blank=True, default=list, help_text='Per-subject final grade/descriptor/status, frozen at generation')),
                ('attendance_summary', models.JSONField(blank=True, default=dict, help_text='Counts by AttendanceStatus for the term')),
                ('narrative', models.TextField(blank=True, default='')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('pdf_key', models.CharField(blank=True, default='', max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='academic.classgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='identity.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='academic.term')),
            ],
            options={
                'db_table': 'report_cards',
                'indexes': [models.Index(fields=['foundation_id', 'student_id', 'term_id', 'is_current'], name='report_card_foundat_624216_idx'), models.Index(fields=['foundation_id', 'class_group_id', 'term_id'], name='report_card_foundat_a5fa64_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_current', True)), fields=('foundation_id', 'student', 'term'), name='unique_current_report_card_per_student_term'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'student', 'term', 'version'), name='unique_report_card_version_per_student_term')],
            },
        ),
    ]
