# Generated by Django 5.1.15 on 2026-09-15 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_reportcardpolicy_reportcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('week_start_date', models.DateField(help_text='Monday of the ISO week this plan covers')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(blank=True, default='')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of {key, filename, size, content_type}')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='academic.classsubject')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('slots', models.ManyToManyField(blank=True, related_name='lesson_plans', to='academic.timetableslot')),
            ],
            options={
                'db_table': 'lesson_plans',
                'indexes': [models.Index(fields=['foundation_id', 'class_subject_id', 'week_start_date'], name='lesson_plan_foundat_3a4301_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'class_subject', 'week_start_date'), name='unique_lesson_plan_per_class_subject_week')],
            },
        ),
    ]
