# Generated by Django 5.1.15 on 2026-09-15 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_lessonplan'),
        ('identity', '0005_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('teacher_can_broadcast', models.BooleanField(default=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='broadcast_policy', to='identity.school')),
            ],
            options={
                'db_table': 'broadcast_policies',
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='broadcasts', to='academic.classgroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='broadcasts_sent', to='identity.staff')),
            ],
            options={
                'db_table': 'broadcasts',
                'indexes': [models.Index(fields=['foundation_id', 'class_group_id', 'sent_at'], name='broadcasts_foundat_bb8623_idx')],
            },
        ),
    ]
