# Generated by Django 5.1.15 on 2026-09-15 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_broadcastpolicy_broadcast'),
        ('identity', '0005_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodGridSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, 'Jumat'), (6, 'Sabtu'), (7, 'Minggu')])),
                ('period_no', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, default='', max_length=64)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='period_grid_slots', to='identity.school')),
            ],
            options={
                'db_table': 'period_grid_slots',
                'indexes': [models.Index(fields=['foundation_id', 'school_id', 'day_of_week'], name='period_grid_foundat_109432_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'school', 'day_of_week', 'period_no'), name='unique_period_grid_slot')],
            },
        ),
    ]
