# Generated by Django 5.1.15 on 2026-09-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_periodgridslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentscore',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Bumped on every update; TCH-007 optimistic concurrency token'),
        ),
    ]
