# Generated by Django 5.1.15 on 2026-09-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_assessmentscore_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='extracurricular_notes',
            field=models.JSONField(blank=True, default=list, help_text="ACD-011 extracurricular notes: list of {'name': str, 'grade': str}"),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='promotion_decision',
            field=models.CharField(blank=True, default='', help_text="e.g. 'NAIK KE KELAS VIII', set manually via set_report_card_content", max_length=64),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='grades_snapshot',
            field=models.JSONField(blank=True, default=list, help_text="Per-subject final grade/descriptor/status, frozen at generation. Each item may also carry an 'objective_narrative' string (ACD-011), set via set_report_card_content."),
        ),
    ]
