# Generated by Django 5.1.15 on 2026-09-15 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_reportcard_extracurricular_notes_and_more'),
        ('identity', '0005_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='academicyear',
            name='unique_academic_year_name_per_school',
        ),
        migrations.RemoveConstraint(
            model_name='assessmentscore',
            name='unique_score_per_assessment_student',
        ),
        migrations.RemoveConstraint(
            model_name='classenrollment',
            name='unique_active_enrollment_per_student_class_group',
        ),
        migrations.RemoveConstraint(
            model_name='classgroup',
            name='unique_class_group_name_per_academic_year',
        ),
        migrations.RemoveConstraint(
            model_name='classsubject',
            name='unique_class_subject_per_term',
        ),
        migrations.RemoveConstraint(
            model_name='examanswer',
            name='unique_answer_per_attempt_question',
        ),
        migrations.RemoveConstraint(
            model_name='examattempt',
            name='unique_attempt_per_exam_student',
        ),
        migrations.RemoveConstraint(
            model_name='examquestion',
            name='unique_question_seq_per_exam',
        ),
        migrations.RemoveConstraint(
            model_name='homeworksubmission',
            name='unique_submission_per_homework_student',
        ),
        migrations.RemoveConstraint(
            model_name='learningobjective',
            name='unique_objective_code_per_subject',
        ),
        migrations.RemoveConstraint(
            model_name='lessonplan',
            name='unique_lesson_plan_per_class_subject_week',
        ),
        migrations.RemoveConstraint(
            model_name='periodgridslot',
            name='unique_period_grid_slot',
        ),
        migrations.RemoveConstraint(
            model_name='reportcard',
            name='unique_current_report_card_per_student_term',
        ),
        migrations.RemoveConstraint(
            model_name='reportcard',
            name='unique_report_card_version_per_student_term',
        ),
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_subject_code_per_school',
        ),
        migrations.RemoveConstraint(
            model_name='term',
            name='unique_term_no_per_academic_year',
        ),
        migrations.RemoveConstraint(
            model_name='timetablesubstitution',
            name='unique_substitution_per_slot_date',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='assessmentscore',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='learningobjective',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='periodgridslot',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='current_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True), ('is_current', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='subject',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='term',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='timetablesubstitution',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'school', 'name', 'active_uniq_marker'), name='unique_academic_year_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='assessmentscore',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'assessment', 'student', 'active_uniq_marker'), name='unique_score_per_assessment_student'),
        ),
        migrations.AddConstraint(
            model_name='classenrollment',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'student', 'class_group', 'active_uniq_marker'), name='unique_active_enrollment_per_student_class_group'),
        ),
        migrations.AddConstraint(
            model_name='classgroup',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'academic_year', 'name', 'active_uniq_marker'), name='unique_class_group_name_per_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'class_group', 'subject', 'term', 'active_uniq_marker'), name='unique_class_subject_per_term'),
        ),
        migrations.AddConstraint(
            model_name='examanswer',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'attempt', 'question', 'active_uniq_marker'), name='unique_answer_per_attempt_question'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'exam', 'student', 'active_uniq_marker'), name='unique_attempt_per_exam_student'),
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'exam', 'seq', 'active_uniq_marker'), name='unique_question_seq_per_exam'),
        ),
        migrations.AddConstraint(
            model_name='homeworksubmission',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'homework', 'student', 'active_uniq_marker'), name='unique_submission_per_homework_student'),
        ),
        migrations.AddConstraint(
            model_name='learningobjective',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'subject', 'code', 'active_uniq_marker'), name='unique_objective_code_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='lessonplan',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'class_subject', 'week_start_date', 'active_uniq_marker'), name='unique_lesson_plan_per_class_subject_week'),
        ),
        migrations.AddConstraint(
            model_name='periodgridslot',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'school', 'day_of_week', 'period_no', 'active_uniq_marker'), name='unique_period_grid_slot'),
        ),
        migrations.AddConstraint(
            model_name='reportcard',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'student', 'term', 'current_uniq_marker'), name='unique_current_report_card_per_student_term'),
        ),
        migrations.AddConstraint(
            model_name='reportcard',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'student', 'term', 'version', 'active_uniq_marker'), name='unique_report_card_version_per_student_term'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'school', 'code', 'active_uniq_marker'), name='unique_subject_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'academic_year', 'term_no', 'active_uniq_marker'), name='unique_term_no_per_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='timetablesubstitution',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'slot', 'date', 'active_uniq_marker'), name='unique_substitution_per_slot_date'),
        ),
    ]
