# Generated by Django 5.2.17 on 2026-09-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_remove_academicyear_unique_academic_year_name_per_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablesubstitution',
            name='decline_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='timetablesubstitution',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetablesubstitution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Menunggu Konfirmasi'), ('ACCEPTED', 'Diterima'), ('DECLINED', 'Ditolak')], default='PENDING', max_length=16),
        ),
    ]
