# Generated by Django 5.1.15 on 2026-09-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_timetablesubstitution_decline_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='dapodik_code',
            field=models.CharField(blank=True, default='', help_text='Ministry subject code for DAPODIK/EMIS export (CMP-017)', max_length=32),
        ),
    ]
