# Generated by Django 5.1.15 on 2026-09-17 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_subject_dapodik_code'),
        ('identity', '0010_person_birth_certificate_number_person_birth_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=256)),
                ('due_at', models.DateTimeField(blank=True, help_text='Acks are closed for new responses after this moment', null=True)),
                ('active_uniq_marker', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField())),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_slips', to='academic.classgroup')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_slips_created', to='identity.staff')),
            ],
            options={
                'db_table': 'permission_slips',
            },
        ),
        migrations.CreateModel(
            name='PermissionSlipAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('response', models.CharField(choices=[('APPROVED', 'Menyetujui (Approved)'), ('DECLINED', 'Menolak (Declined)')], max_length=16)),
                ('responded_at', models.DateTimeField(help_text='Timestamp of the signed acknowledgement (PAR-012)')),
                ('signature', models.CharField(help_text="Guardian's typed full name as the digital signature", max_length=128)),
                ('active_uniq_marker', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField())),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_slip_acknowledgements', to='identity.guardian')),
                ('permission_slip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgements', to='academic.permissionslip')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_slip_acknowledgements', to='identity.student')),
            ],
            options={
                'db_table': 'permission_slip_acknowledgements',
            },
        ),
        migrations.AddIndex(
            model_name='permissionslip',
            index=models.Index(fields=['foundation_id', 'class_group_id', 'due_at'], name='permission__foundat_c5ee7d_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionslip',
            index=models.Index(fields=['foundation_id', 'created_by_id'], name='permission__foundat_bb73ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='permissionslip',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'class_group', 'title', 'active_uniq_marker'), name='unique_active_permission_slip_title_per_class_group'),
        ),
        migrations.AddIndex(
            model_name='permissionslipacknowledgement',
            index=models.Index(fields=['foundation_id', 'permission_slip_id', 'student_id'], name='permission__foundat_3c82dc_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionslipacknowledgement',
            index=models.Index(fields=['foundation_id', 'guardian_id'], name='permission__foundat_43d26d_idx'),
        ),
        migrations.AddConstraint(
            model_name='permissionslipacknowledgement',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'permission_slip', 'student', 'guardian', 'active_uniq_marker'), name='unique_active_ack_per_slip_student_guardian'),
        ),
    ]
