# Generated by Django 5.2.17 on 2026-09-17 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_par012_permission_slips'),
        ('calendar_sync', '0001_initial'),
        ('identity', '0012_microsofttenantconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(choices=[('HOLIDAY', 'Hari Libur / Cuti'), ('EXAM', 'Jadwal Ujian'), ('TIMETABLE_EXCEPTION', 'Pengecualian Jadwal / Pembatalan Sesi'), ('STAFF_MEETING', 'Rapat Staf / Guru'), ('SCHOOL_EVENT', 'Kegiatan Sekolah / Upacara'), ('OTHER', 'Lainnya')], db_index=True, default='OTHER', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(db_index=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('affects_attendance', models.BooleanField(default=False, help_text='Jika True, sesi jadwal pada rentang ini dikecualikan/diliburkan dari absensi')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('SYNCED', 'Synced Calendar')], default='MANUAL', max_length=16)),
                ('active_uniq_marker', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField())),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_calendar_events', to='academic.academicyear')),
                ('class_groups', models.ManyToManyField(blank=True, help_text='Kosong berarti berlaku untuk seluruh sekolah', related_name='academic_calendar_events', to='academic.classgroup')),
                ('exam', models.ForeignKey(blank=True, help_text='Tautan ke jadwal ujian jika acara ini dipetakan sebagai ujian', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='academic.exam')),
                ('external_event', models.ForeignKey(blank=True, help_text='Tautan ke acara kalender eksternal sumber sinkronisasi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_events', to='calendar_sync.externalcalendarevent')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_calendar_events', to='identity.school')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_calendar_events', to='academic.term')),
            ],
            options={
                'verbose_name': 'Acara Kalender Akademik',
                'verbose_name_plural': 'Daftar Acara Kalender Akademik',
                'db_table': 'academic_calendar_events',
                'indexes': [models.Index(fields=['foundation_id', 'school_id', 'start_at'], name='academic_ca_foundat_926422_idx'), models.Index(fields=['foundation_id', 'event_type', 'start_at'], name='academic_ca_foundat_517f4b_idx'), models.Index(fields=['foundation_id', 'external_event_id'], name='academic_ca_foundat_65a13c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CalendarAcademicSyncPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('auto_sync_enabled', models.BooleanField(default=False, help_text='Opt-in: izinkan sinkronisasi otomatis dari kalender eksternal ke kalender akademik')),
                ('auto_create_exams', models.BooleanField(default=False, help_text='Opt-in: otomatis buat entri Exam draf jika acara kalender bertipe UJIAN')),
                ('tag_prefix', models.CharField(blank=True, default='[EDUCORE]', help_text='Prefix penanda eksplisit pada judul kalender (opsional)', max_length=32)),
                ('custom_keywords', models.JSONField(blank=True, default=dict, help_text='Konfigurasi kata kunci kustom per tipe acara')),
                ('active_uniq_marker', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField())),
                ('school', models.ForeignKey(blank=True, help_text='Null berarti kebijakan bawaan tingkat yayasan', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calendar_sync_policies', to='identity.school')),
            ],
            options={
                'verbose_name': 'Kebijakan Sinkronisasi Kalender Akademik',
                'verbose_name_plural': 'Daftar Kebijakan Sinkronisasi Kalender Akademik',
                'db_table': 'calendar_academic_sync_policies',
                'constraints': [models.UniqueConstraint(fields=('foundation_id', 'school', 'active_uniq_marker'), name='unique_active_calendar_sync_policy_per_school')],
            },
        ),
    ]
