# Generated by Django 5.1.15 on 2026-09-17 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider', models.CharField(choices=[('google', 'Google Workspace'), ('microsoft', 'Microsoft 365')], db_index=True, max_length=16)),
                ('provider_email', models.EmailField(blank=True, default='', max_length=255)),
                ('access_token_encrypted', models.TextField(help_text='Fernet-encrypted OAuth access token')),
                ('refresh_token_encrypted', models.TextField(blank=True, default='', help_text='Fernet-encrypted OAuth refresh token; blank when the provider did not issue one')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Expiry of the stored access token (tz-aware)', null=True)),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('ERROR', 'Error'), ('REVOKED', 'Revoked')], default='CONNECTED', max_length=16)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('calendar_id', models.CharField(default='primary', help_text='Provider calendar identifier being synced', max_length=255)),
                ('sync_cursor', models.CharField(blank=True, default='', help_text='Provider incremental-sync cursor (Google syncToken / Graph deltaLink); reserved — the current pull uses a plain time window', max_length=2048)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('active_uniq_marker', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField())),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendar_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Koneksi Kalender Eksternal',
                'verbose_name_plural': 'Daftar Koneksi Kalender Eksternal',
                'db_table': 'calendar_connections',
            },
        ),
        migrations.CreateModel(
            name='ExternalCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider_event_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=512)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField()),
                ('is_all_day', models.BooleanField(default=False)),
                ('meeting_url', models.URLField(blank=True, default='', help_text='Video-conference link (Google hangoutLink / Microsoft Teams joinUrl)', max_length=1024)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('active_uniq_marker', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField())),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='calendar_sync.calendarconnection')),
            ],
            options={
                'verbose_name': 'Acara Kalender Eksternal',
                'verbose_name_plural': 'Daftar Acara Kalender Eksternal',
                'db_table': 'external_calendar_events',
            },
        ),
        migrations.AddIndex(
            model_name='calendarconnection',
            index=models.Index(fields=['foundation_id', 'status'], name='calendar_co_foundat_5fe736_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarconnection',
            index=models.Index(fields=['foundation_id', 'user'], name='calendar_co_foundat_b1eada_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarconnection',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'user', 'provider', 'active_uniq_marker'), name='unique_active_calendar_connection_per_provider'),
        ),
        migrations.AddIndex(
            model_name='externalcalendarevent',
            index=models.Index(fields=['foundation_id', 'connection', 'start_at'], name='external_ca_foundat_b9a509_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalcalendarevent',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'connection', 'provider_event_id', 'active_uniq_marker'), name='unique_active_external_event_per_connection'),
        ),
    ]
