# Generated by Django 5.2.17 on 2026-09-15 00:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0005_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('RFID', 'RFID (MIFARE DESFire)'), ('NFC', 'NFC'), ('QR', 'QR Code Fallback')], db_index=True, default='RFID', max_length=16)),
                ('uid', models.CharField(db_index=True, help_text='Card UID hex string or QR cryptographic payload token', max_length=128)),
                ('card_number', models.CharField(blank=True, default='', help_text='Human-readable printed card identifier', max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=16)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiry timestamp for temporary credentials (HW-020: <=15 min QR)', null=True)),
                ('is_used', models.BooleanField(default=False, help_text='Single-use flag for temporary QR fallback credentials')),
                ('replacement_fee_posted', models.BooleanField(default=False, help_text='Flag indicating replacement fee was posted to invoice (HW-018)')),
                ('staff', models.ForeignKey(blank=True, help_text='Linked staff member (if issued to a staff member)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='identity.staff')),
                ('student', models.ForeignKey(blank=True, help_text='Linked student (if issued to a student)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='identity.student')),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
                'db_table': 'credentials',
                'abstract': False,
                'indexes': [models.Index(fields=['foundation_id', 'uid'], name='idx_cred_fnd_uid'), models.Index(fields=['foundation_id', 'student', 'status'], name='idx_cred_fnd_stu_st'), models.Index(fields=['foundation_id', 'staff', 'status'], name='idx_cred_fnd_stf_st'), models.Index(fields=['foundation_id', 'type', 'status'], name='idx_cred_fnd_type_st')],
            },
        ),
    ]
