# Generated by Django 5.2.17 on 2026-09-15 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('hardware', '0001_initial'),
        ('identity', '0005_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('HADIR', 'Hadir (Present)'), ('TERLAMBAT', 'Terlambat (Late)'), ('SAKIT', 'Sakit (Excused)'), ('IZIN', 'Izin (Permitted)'), ('ALPA', 'Alpa (Unexcused Absence)'), ('DISPEN', 'Dispensasi (Sanctioned)')], db_index=True, default='ALPA', max_length=16)),
                ('first_in_at', models.DateTimeField(blank=True, null=True)),
                ('last_out_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('GATE', 'Gate Scan'), ('TEACHER', 'Teacher / Class Attendance'), ('SYSTEM', 'System Default (Cutoff)'), ('MANUAL', 'Manual Staff Override')], default='GATE', max_length=32)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('is_override', models.BooleanField(default=False, help_text='Whether this record was manually overridden by staff (ATT-003)')),
                ('original_status', models.CharField(blank=True, default='', help_text='Original derived status before staff override', max_length=16)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_days', to='identity.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_days', to='identity.student')),
            ],
            options={
                'verbose_name': 'Daily Attendance',
                'verbose_name_plural': 'Daily Attendances',
                'db_table': 'attendance_days',
                'abstract': False,
                'indexes': [models.Index(fields=['foundation_id', 'school', 'date', 'status'], name='idx_attday_fnd_sch_dt_st'), models.Index(fields=['foundation_id', 'student', 'date'], name='idx_attday_fnd_stu_dt')],
                'constraints': [models.UniqueConstraint(fields=('foundation_id', 'school', 'student', 'date'), name='unique_student_attendance_per_date')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('late_after_time', models.TimeField(default='07:15:00', help_text='Time after which an IN scan is marked TERLAMBAT instead of HADIR')),
                ('absent_cutoff_time', models.TimeField(default='09:00:00', help_text='Cutoff time after which students with no scan are marked ALPA')),
                ('debounce_seconds', models.PositiveIntegerField(default=120, help_text='Seconds within which duplicate scans are ignored for notification (ATT-007)')),
                ('school', models.ForeignKey(help_text='School where this rule applies', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_rules', to='identity.school')),
            ],
            options={
                'verbose_name': 'Attendance Rule',
                'verbose_name_plural': 'Attendance Rules',
                'db_table': 'attendance_rules',
                'abstract': False,
                'indexes': [models.Index(fields=['foundation_id', 'deleted_at'], name='attendance__foundat_9e00f7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'school'), name='unique_active_attendance_rule_per_school')],
            },
        ),
        migrations.CreateModel(
            name='GateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event_uuid', models.UUIDField(db_index=True, help_text='Client-generated idempotent UUID from edge gateway (HW-005)', unique=True)),
                ('raw_uid', models.CharField(blank=True, default='', help_text='Scanned card UID or QR string from reader', max_length=128)),
                ('direction', models.CharField(choices=[('IN', 'Masuk (In)'), ('OUT', 'Keluar (Out)')], default='IN', max_length=16)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('method', models.CharField(choices=[('RFID', 'RFID / Smart Card'), ('FACE', 'Face Recognition'), ('MANUAL', 'Manual Check-in'), ('KIOSK', 'Kiosk')], default='RFID', max_length=16)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, help_text='Match confidence score for face recognition terminals (ATT-010)', max_digits=5, null=True)),
                ('photo_key', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_index=True, default='ACCEPTED', max_length=16)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_duplicate_scan', models.BooleanField(default=False, help_text='Marked True if scanned within debounce window (ATT-007)')),
                ('replayed', models.BooleanField(default=False, help_text='Marked True if buffered offline and replayed on reconnect (ATT-012)')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_events', to='attendance.credential')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_events', to='hardware.device')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_events', to='identity.school')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_events', to='identity.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_events', to='identity.student')),
            ],
            options={
                'verbose_name': 'Gate Event',
                'verbose_name_plural': 'Gate Events',
                'db_table': 'gate_events',
                'abstract': False,
                'indexes': [models.Index(fields=['foundation_id', 'school', 'occurred_at'], name='idx_gtevt_fnd_sch_occ'), models.Index(fields=['foundation_id', 'student', 'occurred_at'], name='idx_gtevt_fnd_stu_occ'), models.Index(fields=['foundation_id', 'status'], name='idx_gtevt_fnd_st')],
            },
        ),
    ]
