# Generated by Django 5.1.15 on 2026-09-15 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_reportcardpolicy_reportcard'),
        ('attendance', '0002_attendanceday_attendancerule_gateevent'),
        ('identity', '0005_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('HADIR', 'Hadir (Present)'), ('TERLAMBAT', 'Terlambat (Late)'), ('SAKIT', 'Sakit (Excused)'), ('IZIN', 'Izin (Permitted)'), ('ALPA', 'Alpa (Unexcused Absence)'), ('DISPEN', 'Dispensasi (Sanctioned)')], default='HADIR', max_length=16)),
                ('source', models.CharField(choices=[('TEACHER', 'Guru (Teacher)'), ('GATE_PREFILL', 'Pra-isi dari Gerbang (Gate Pre-fill)')], default='TEACHER', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='period_attendances', to='academic.timetableslot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='period_attendances', to='identity.student')),
            ],
            options={
                'verbose_name': 'Absensi Per Jam Pelajaran',
                'verbose_name_plural': 'Absensi Per Jam Pelajaran',
                'db_table': 'period_attendances',
                'abstract': False,
                'indexes': [models.Index(fields=['foundation_id', 'slot_id', 'date'], name='period_atte_foundat_2b8dd8_idx'), models.Index(fields=['foundation_id', 'student_id', 'date'], name='period_atte_foundat_dbf3a8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'student', 'slot', 'date'), name='unique_period_attendance_per_student_slot_date')],
            },
        ),
    ]
