# Generated by Django 5.1.15 on 2026-09-15 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_remove_academicyear_unique_academic_year_name_per_school_and_more'),
        ('attendance', '0003_periodattendance'),
        ('identity', '0005_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancerule',
            name='unique_active_attendance_rule_per_school',
        ),
        migrations.RemoveConstraint(
            model_name='periodattendance',
            name='unique_period_attendance_per_student_slot_date',
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='periodattendance',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddConstraint(
            model_name='attendancerule',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'school', 'active_uniq_marker'), name='unique_active_attendance_rule_per_school'),
        ),
        migrations.AddConstraint(
            model_name='periodattendance',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'student', 'slot', 'date', 'active_uniq_marker'), name='unique_period_attendance_per_student_slot_date'),
        ),
    ]
