# Generated by Django 5.2.17 on 2026-09-17 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_attendancerule_unique_active_attendance_rule_per_school_and_more'),
        ('identity', '0008_alter_roleassignment_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date_from', models.DateField(db_index=True, help_text='Tanggal mulai ketidakhadiran')),
                ('date_to', models.DateField(db_index=True, help_text='Tanggal akhir ketidakhadiran (inklusif)')),
                ('type', models.CharField(choices=[('SAKIT', 'Sakit (Sick / Medical)'), ('IZIN', 'Izin (Permitted)')], db_index=True, default='SAKIT', max_length=16)),
                ('reason', models.TextField(help_text='Alasan pengajuan izin atau keterangan sakit')),
                ('attachment_key', models.CharField(blank=True, default='', help_text='Kunci StoredFile untuk berkas lampiran foto surat dokter/izin', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu (Pending)'), ('APPROVED', 'Disetujui (Approved)'), ('REJECTED', 'Ditolak (Rejected)')], db_index=True, default='PENDING', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, help_text='Waktu keputusan diproses', null=True)),
                ('decision_note', models.TextField(blank=True, default='', help_text='Catatan keputusan dari staf')),
                ('decided_by', models.ForeignKey(blank=True, help_text='Staf yang memproses persetujuan atau penolakan', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_absence_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='Orang tua / wali yang mengajukan permohonan', on_delete=django.db.models.deletion.PROTECT, related_name='submitted_absence_requests', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(help_text='Sekolah tempat siswa terdaftar', on_delete=django.db.models.deletion.PROTECT, related_name='absence_requests', to='identity.school')),
                ('student', models.ForeignKey(help_text='Siswa yang dimohonkan izin/sakit', on_delete=django.db.models.deletion.PROTECT, related_name='absence_requests', to='identity.student')),
            ],
            options={
                'verbose_name': 'Permohonan Izin / Sakit',
                'verbose_name_plural': 'Permohonan Izin / Sakit',
                'db_table': 'absence_requests',
                'abstract': False,
                'indexes': [models.Index(fields=['foundation_id', 'student', 'status'], name='idx_absreq_fnd_stu_st'), models.Index(fields=['foundation_id', 'school', 'status'], name='idx_absreq_fnd_sch_st'), models.Index(fields=['foundation_id', 'date_from', 'date_to'], name='idx_absreq_fnd_dt')],
            },
        ),
    ]
