# Generated by Django 5.1.15 on 2026-09-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_absencerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodattendance',
            name='source',
            field=models.CharField(choices=[('TEACHER', 'Guru (Teacher)'), ('GATE_PREFILL', 'Pra-isi dari Gerbang (Gate Pre-fill)'), ('MANUAL', 'Override Manual (mis. Klinik/UKS)')], default='TEACHER', max_length=16),
        ),
    ]
