# Generated by Django 5.1.15 on 2026-09-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_periodattendance_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateEventArchive',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField()),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_uuid', models.UUIDField(help_text='Client-generated idempotent UUID from edge gateway (HW-005)')),
                ('school_id', models.BigIntegerField(db_column='school_id')),
                ('device_id', models.BigIntegerField(db_column='device_id')),
                ('student_id', models.BigIntegerField(db_column='student_id', null=True)),
                ('staff_id', models.BigIntegerField(db_column='staff_id', null=True)),
                ('credential_id', models.BigIntegerField(db_column='credential_id', null=True)),
                ('raw_uid', models.CharField(blank=True, default='', help_text='Scanned card UID or QR string from reader', max_length=128)),
                ('direction', models.CharField(choices=[('IN', 'Masuk (In)'), ('OUT', 'Keluar (Out)')], default='IN', max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('method', models.CharField(choices=[('RFID', 'RFID / Smart Card'), ('FACE', 'Face Recognition'), ('MANUAL', 'Manual Check-in'), ('KIOSK', 'Kiosk')], default='RFID', max_length=16)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, help_text='Match confidence score for face recognition terminals (ATT-010)', max_digits=5, null=True)),
                ('photo_key', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='ACCEPTED', max_length=16)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_duplicate_scan', models.BooleanField(default=False, help_text='Marked True if scanned within debounce window (ATT-007)')),
                ('replayed', models.BooleanField(default=False, help_text='Marked True if buffered offline and replayed on reconnect (ATT-012)')),
            ],
            options={
                'db_table': 'gate_events_archive',
                'default_permissions': (),
            },
        ),
    ]
