# Generated by Django 5.1.15 on 2026-09-19 08:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_gateeventarchive'),
        ('identity', '0018_role_choice_labels_indonesian'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('person_name', models.CharField(max_length=120)),
                ('relation', models.CharField(blank=True, default='', max_length=64)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('photo_key', models.CharField(blank=True, default='', max_length=500)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(db_index=True)),
                ('one_time', models.BooleanField(default=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_authorizations', to='identity.guardian')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_authorizations', to='identity.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_authorizations', to='identity.student')),
            ],
            options={
                'db_table': 'pickup_authorizations',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PickupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('picked_up_by', models.CharField(max_length=120)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('QR', 'QR penjemputan (QR pickup)'), ('GUARDIAN', 'Wali terdaftar (Registered guardian)'), ('OVERRIDE', 'Pengecualian admin sekolah (School admin override)')], db_index=True, max_length=16)),
                ('override_reason', models.TextField(blank=True, default='')),
                ('authorization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='attendance.pickupauthorization')),
                ('authorized_by_guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.guardian')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_events', to='identity.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_events', to='identity.student')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pickup_events',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='pickupauthorization',
            index=models.Index(fields=['foundation_id', 'student', 'valid_to'], name='idx_pickauth_fnd_stu_to'),
        ),
        migrations.AddIndex(
            model_name='pickupauthorization',
            index=models.Index(fields=['foundation_id', 'school', 'valid_to'], name='idx_pickauth_fnd_sch_to'),
        ),
        migrations.AddIndex(
            model_name='pickupevent',
            index=models.Index(fields=['foundation_id', 'school', 'occurred_at'], name='idx_pickev_fnd_sch_at'),
        ),
        migrations.AddIndex(
            model_name='pickupevent',
            index=models.Index(fields=['foundation_id', 'student', 'occurred_at'], name='idx_pickev_fnd_stu_at'),
        ),
    ]
