# Generated by Django 5.1.15 on 2026-09-19 13:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_pickupauthorization_pickupevent_and_more'),
        ('hardware', '0004_biometrictemplate'),
        ('identity', '0020_user_activity_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('approach_minutes', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('active_uniq_marker', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField())),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_routes', to='identity.school')),
            ],
            options={
                'db_table': 'bus_routes',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('direction', models.CharField(choices=[('TO_SCHOOL', 'Berangkat ke sekolah (To school)'), ('FROM_SCHOOL', 'Pulang dari sekolah (From school)')], max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Berjalan (Active)'), ('COMPLETED', 'Selesai (Completed)')], db_index=True, default='ACTIVE', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_speed_mps', models.FloatField(blank=True, null=True)),
                ('last_position_at', models.DateTimeField(blank=True, null=True)),
                ('announced_stop_ids', models.JSONField(blank=True, default=list)),
                ('unaccounted_checked_at', models.DateTimeField(blank=True, null=True)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='attendance.busroute')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_runs', to='identity.school')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bus_runs',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusBoardingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event_uuid', models.UUIDField(unique=True)),
                ('kind', models.CharField(choices=[('BOARD', 'Naik (Board)'), ('ALIGHT', 'Turun (Alight)')], max_length=8)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('replayed', models.BooleanField(default=False)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hardware.device')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_events', to='identity.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_events', to='identity.student')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='attendance.busrun')),
            ],
            options={
                'db_table': 'bus_boarding_events',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_m', models.PositiveIntegerField(default=150)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stops', to='attendance.busroute')),
            ],
            options={
                'db_table': 'bus_stops',
                'ordering': ['sequence', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusStopAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('active_uniq_marker', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField())),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='attendance.busroute')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='attendance.busstop')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_assignments', to='identity.student')),
            ],
            options={
                'db_table': 'bus_stop_assignments',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='busroute',
            index=models.Index(fields=['foundation_id', 'school', 'is_active'], name='idx_busroute_fnd_sch_act'),
        ),
        migrations.AddConstraint(
            model_name='busroute',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'school', 'name', 'active_uniq_marker'), name='unique_active_bus_route_name'),
        ),
        migrations.AddIndex(
            model_name='busrun',
            index=models.Index(fields=['foundation_id', 'route', 'status'], name='idx_busrun_fnd_rt_st'),
        ),
        migrations.AddIndex(
            model_name='busrun',
            index=models.Index(fields=['foundation_id', 'status', 'unaccounted_checked_at'], name='idx_busrun_fnd_st_chk'),
        ),
        migrations.AddIndex(
            model_name='busboardingevent',
            index=models.Index(fields=['foundation_id', 'run', 'student', 'occurred_at'], name='idx_busev_fnd_run_stu_at'),
        ),
        migrations.AddIndex(
            model_name='busstop',
            index=models.Index(fields=['foundation_id', 'route', 'sequence'], name='idx_busstop_fnd_rt_seq'),
        ),
        migrations.AddIndex(
            model_name='busstopassignment',
            index=models.Index(fields=['foundation_id', 'student'], name='idx_busasg_fnd_stu'),
        ),
        migrations.AddIndex(
            model_name='busstopassignment',
            index=models.Index(fields=['foundation_id', 'stop'], name='idx_busasg_fnd_stop'),
        ),
        migrations.AddConstraint(
            model_name='busstopassignment',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'route', 'student', 'active_uniq_marker'), name='unique_active_bus_assignment_per_route'),
        ),
    ]
