# Generated by Django 5.1.15 on 2026-09-15 03:05

import apps.core.fields
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0005_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('daily_limit', apps.core.fields.MoneyField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('blocked_categories', models.JSONField(blank=True, default=list)),
                ('blocked_products', models.JSONField(blank=True, default=list, help_text='List of product SKUs')),
                ('allowed_window_start', models.TimeField(blank=True, null=True)),
                ('allowed_window_end', models.TimeField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='spend_rule', to='identity.student')),
            ],
            options={
                'db_table': 'spend_rules',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('balance', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('FROZEN', 'Dibekukan'), ('CLOSED', 'Ditutup')], default='ACTIVE', max_length=16)),
                ('daily_limit', apps.core.fields.MoneyField(blank=True, decimal_places=2, help_text='Guardian-configured daily spend limit (WAL-009)', max_digits=18, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='identity.student')),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('TOPUP', 'Isi Ulang'), ('PURCHASE', 'Pembelian'), ('REFUND', 'Pengembalian'), ('ADJUSTMENT', 'Penyesuaian'), ('TRANSFER_OUT', 'Transfer Keluar')], max_length=16)),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, help_text='Signed delta: positive for TOPUP/REFUND, negative for PURCHASE/TRANSFER_OUT', max_digits=18)),
                ('balance_after', apps.core.fields.MoneyField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(blank=True, default='', max_length=128)),
                ('occurred_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('COMPLETED', 'Selesai'), ('REJECTED', 'Ditolak')], default='COMPLETED', max_length=16)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'db_table': 'wallet_transactions',
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['foundation_id', 'status'], name='wallets_foundat_46617c_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['foundation_id', 'wallet_id', 'occurred_at'], name='wallet_tran_foundat_f3dc6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'wallet', 'idempotency_key'), name='unique_wallet_transaction_idempotency_key'),
        ),
    ]
