# Generated by Django 5.1.15 on 2026-09-15 03:23

import apps.core.fields
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_staff'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('CANTEEN', 'Kantin'), ('UNIFORM', 'Seragam'), ('STATIONERY', 'Alat Tulis'), ('OTHER', 'Lainnya')], default='CANTEEN', max_length=16)),
                ('settlement_account', models.CharField(blank=True, default='', max_length=64)),
                ('commission_bps', models.PositiveIntegerField(default=0, help_text='Commission in basis points (100 = 1%)')),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchants', to='identity.school')),
            ],
            options={
                'db_table': 'merchants',
            },
        ),
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('device_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('INACTIVE', 'Nonaktif')], default='ACTIVE', max_length=16)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminals', to='wallet.merchant')),
            ],
            options={
                'db_table': 'pos_terminals',
            },
        ),
        migrations.CreateModel(
            name='POSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('items', models.JSONField(default=list, help_text='List of {sku, name, qty, unit_price}')),
                ('subtotal', apps.core.fields.MoneyField(decimal_places=2, max_digits=18)),
                ('commission', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total', apps.core.fields.MoneyField(decimal_places=2, max_digits=18)),
                ('occurred_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('COMPLETED', 'Selesai'), ('REJECTED', 'Ditolak'), ('VOIDED', 'Dibatalkan')], default='COMPLETED', max_length=16)),
                ('offline_created', models.BooleanField(default=False)),
                ('client_transaction_id', models.CharField(db_index=True, max_length=128)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, default='', max_length=255)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_transactions', to='wallet.merchant')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_transactions', to='identity.student')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_transactions', to='wallet.posterminal')),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.wallettransaction')),
            ],
            options={
                'db_table': 'pos_transactions',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('price', apps.core.fields.MoneyField(decimal_places=2, max_digits=18)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('nutrition', models.JSONField(blank=True, default=dict, help_text='e.g. {calories, sugar_g}')),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='wallet.merchant')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['foundation_id', 'school_id', 'is_active'], name='merchants_foundat_a190db_idx'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['foundation_id', 'merchant_id', 'occurred_at'], name='pos_transac_foundat_922b48_idx'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['foundation_id', 'student_id', 'occurred_at'], name='pos_transac_foundat_b4dbb7_idx'),
        ),
        migrations.AddConstraint(
            model_name='postransaction',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'terminal', 'client_transaction_id'), name='unique_pos_transaction_client_id_per_terminal'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['foundation_id', 'merchant_id', 'is_active'], name='products_foundat_c76960_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'merchant', 'sku'), name='unique_product_sku_per_merchant'),
        ),
    ]
