# Generated by Django 5.1.15 on 2026-09-15 03:39

import apps.core.fields
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_merchant_posterminal_postransaction_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gross', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('commission', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu'), ('PAID', 'Dibayar')], default='PENDING', max_length=16)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('statement_pdf_key', models.CharField(blank=True, default='', max_length=255)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='wallet.merchant')),
            ],
            options={
                'db_table': 'merchant_settlements',
                'indexes': [models.Index(fields=['foundation_id', 'merchant_id', 'period_start'], name='merchant_se_foundat_d93964_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'merchant', 'period_start', 'period_end'), name='unique_settlement_per_merchant_period')],
            },
        ),
    ]
