# Generated by Django 5.1.15 on 2026-09-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_merchantsettlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='requires_reconciliation',
            field=models.BooleanField(default=False, help_text='Set when an offline overspend was accepted and took the wallet negative (WAL-017)'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Selesai'), ('REJECTED', 'Ditolak'), ('RECONCILE_REQUIRED', 'Perlu Rekonsiliasi')], default='COMPLETED', max_length=24),
        ),
    ]
