# Generated by Django 5.1.15 on 2026-09-15 05:20

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payments_and_ledger'),
        ('identity', '0005_staff'),
        ('wallet', '0004_wallet_requires_reconciliation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('trigger', models.CharField(choices=[('OFFLINE_OVERSPEND', 'Kelebihan Belanja Luring'), ('SYNC_DRIFT', 'Selisih Sinkronisasi'), ('MANUAL_ADJUSTMENT', 'Penyesuaian Manual')], max_length=24)),
                ('shortfall', apps.core.fields.MoneyField(decimal_places=2, help_text='Absolute value of the negative balance at detection (REC-002)', max_digits=18)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('balance_at_detection', apps.core.fields.MoneyField(decimal_places=2, max_digits=18)),
                ('detected_at', models.DateTimeField()),
                ('detected_by_job', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('OPEN', 'Terbuka'), ('SETTLED', 'Diselesaikan'), ('WRITTEN_OFF', 'Dihapusbukukan'), ('INVOICED', 'Ditagihkan')], default='OPEN', max_length=16)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('notice_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('invoiced_at', models.DateTimeField(blank=True, null=True)),
                ('write_off_reason', models.CharField(blank=True, default='', max_length=255)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.invoice')),
                ('pos_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to='wallet.postransaction')),
                ('settled_by_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.wallettransaction')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_reconciliations', to='identity.student')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='wallet.wallet')),
                ('written_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_reconciliations',
                'indexes': [models.Index(fields=['foundation_id', 'wallet_id', 'status'], name='wallet_reco_foundat_8431db_idx'), models.Index(fields=['foundation_id', 'status', 'detected_at'], name='wallet_reco_foundat_009956_idx')],
            },
        ),
    ]
