# Generated by Django 5.1.15 on 2026-09-15 05:52

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_staff'),
        ('wallet', '0005_walletreconciliation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletRefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu'), ('PAID', 'Dibayar'), ('DONATED', 'Didonasikan')], default='PENDING', max_length=16)),
                ('requested_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('guardian_bank_name', models.CharField(blank=True, default='', max_length=64)),
                ('guardian_bank_account_number', models.CharField(blank=True, default='', max_length=64)),
                ('guardian_account_holder_name', models.CharField(blank=True, default='', max_length=128)),
                ('donation_consent', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_refund_requests', to='identity.student')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='wallet.wallet')),
            ],
            options={
                'db_table': 'wallet_refund_requests',
                'indexes': [models.Index(fields=['foundation_id', 'status'], name='wallet_refu_foundat_4ed7f8_idx'), models.Index(fields=['foundation_id', 'wallet_id', 'status'], name='wallet_refu_foundat_964cbf_idx')],
            },
        ),
    ]
