# Generated by Django 5.1.15 on 2026-09-15 06:01

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_staff'),
        ('wallet', '0006_walletrefundrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTopupIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('method', models.CharField(choices=[('CASH', 'Tunai di Kantor Sekolah'), ('MANUAL', 'Penyesuaian Manual'), ('VA', 'Virtual Account'), ('QRIS', 'QRIS')], max_length=8)),
                ('provider', models.CharField(default='MOCK', max_length=16)),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('va_bank', models.CharField(blank=True, default='', max_length=16)),
                ('va_number', models.CharField(blank=True, default='', max_length=32)),
                ('qris_payload', models.CharField(blank=True, default='', max_length=255)),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Pembayaran'), ('SETTLED', 'Selesai'), ('EXPIRED', 'Kedaluwarsa'), ('FAILED', 'Gagal')], default='PENDING', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_topup_intents', to='identity.student')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topup_intents', to='wallet.wallet')),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.wallettransaction')),
            ],
            options={
                'db_table': 'wallet_topup_intents',
                'indexes': [models.Index(fields=['foundation_id', 'wallet_id', 'status'], name='wallet_topu_foundat_62fcc8_idx')],
            },
        ),
    ]
