# Generated by Django 5.1.15 on 2026-09-15 15:28

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_wallettopupintent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAutoTopupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Explicit opt-in required (WAL-006)')),
                ('threshold_amount', apps.core.fields.MoneyField(decimal_places=2, help_text='Auto-top-up triggers when balance drops below this', max_digits=18)),
                ('topup_amount', apps.core.fields.MoneyField(decimal_places=2, help_text='Amount requested each time auto-top-up triggers', max_digits=18)),
                ('method', models.CharField(choices=[('CASH', 'Tunai di Kantor Sekolah'), ('MANUAL', 'Penyesuaian Manual'), ('VA', 'Virtual Account'), ('QRIS', 'QRIS')], default='VA', max_length=8)),
                ('bank', models.CharField(blank=True, default='', max_length=16)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='auto_topup_config', to='wallet.wallet')),
            ],
            options={
                'db_table': 'wallet_auto_topup_configs',
            },
        ),
    ]
