# Generated by Django 5.1.15 on 2026-09-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_walletautotopupconfig'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='merchantsettlement',
            name='unique_settlement_per_merchant_period',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_sku_per_merchant',
        ),
        migrations.AddField(
            model_name='merchantsettlement',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='product',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddConstraint(
            model_name='merchantsettlement',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'merchant', 'period_start', 'period_end', 'active_uniq_marker'), name='unique_settlement_per_merchant_period'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'merchant', 'sku', 'active_uniq_marker'), name='unique_product_sku_per_merchant'),
        ),
    ]
