# Generated by Django 5.1.15 on 2026-09-19 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0016_school_qr_self_amount_max'),
        ('wallet', '0009_remove_merchantsettlement_unique_settlement_per_merchant_period_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='qr_self_amount_ack_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='qr_self_amount_ack_by',
            field=models.ForeignKey(blank=True, help_text='Admin who acknowledged the operator-verifies-amount statement (QRS-001)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchant',
            name='qr_self_amount_enabled',
            field=models.BooleanField(default=False, help_text='Student-entered QR Charge accepted at this merchant (QRS-001)'),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='confirmation_code',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='entry_mode',
            field=models.CharField(choices=[('OPERATOR', 'Diinput petugas'), ('SELF_ENTERED', 'Diinput siswa')], default='OPERATOR', max_length=16),
        ),
        migrations.AddField(
            model_name='spendrule',
            name='qr_charge_enabled',
            field=models.BooleanField(default=True, help_text='Guardian switch for student-entered QR Charge (QRS-002)'),
        ),
        migrations.CreateModel(
            name='POSQRSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nonce', models.CharField(max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_by_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.student')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qr_sessions', to='wallet.merchant')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qr_sessions', to='wallet.posterminal')),
            ],
            options={
                'db_table': 'pos_qr_sessions',
            },
        ),
        migrations.AddField(
            model_name='postransaction',
            name='qr_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wallet.posqrsession'),
        ),
        migrations.AddIndex(
            model_name='posqrsession',
            index=models.Index(fields=['foundation_id', 'terminal_id', 'expires_at'], name='pos_qr_sess_foundat_611511_idx'),
        ),
    ]
