# Generated by Django 5.1.15 on 2026-09-19 00:26

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0016_school_qr_self_amount_max'),
        ('wallet', '0010_qr_charge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='qr_dispute_flagged_at',
            field=models.DateTimeField(blank=True, help_text='Raised when 3+ QR disputes are upheld in 30 days; cleared on school-admin review (QRS-028)', null=True),
        ),
        migrations.CreateModel(
            name='QRDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reason', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('OPEN', 'Terbuka'), ('UPHELD', 'Dikabulkan'), ('REJECTED', 'Ditolak')], default='OPEN', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, default='', max_length=500)),
                ('refund_amount', apps.core.fields.MoneyField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qr_disputes', to='wallet.merchant')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pos_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='wallet.postransaction')),
                ('resolution_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.wallettransaction')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.student')),
            ],
            options={
                'db_table': 'pos_qr_disputes',
                'indexes': [models.Index(fields=['foundation_id', 'merchant_id', 'status'], name='pos_qr_disp_foundat_5f39cb_idx'), models.Index(fields=['foundation_id', 'student_id'], name='pos_qr_disp_foundat_30ae98_idx')],
            },
        ),
    ]
