# Generated by Django 5.1.15 on 2026-09-19 00:59

import apps.core.fields
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_qr_disputes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='static_qr_ack_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='static_qr_ack_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchant',
            name='static_qr_enabled',
            field=models.BooleanField(default=False, help_text='Printed static QR decals accepted at this merchant; separate from QR Charge itself (QRS-008)'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='static_qr_max',
            field=apps.core.fields.MoneyField(decimal_places=2, default=Decimal('25000.00'), help_text='Per-charge cap for static decals; the lower of this and the school cap applies', max_digits=18),
        ),
        migrations.AlterField(
            model_name='postransaction',
            name='terminal',
            field=models.ForeignKey(blank=True, help_text='Null for a static-decal charge, which has no terminal (QRS-040 keys it on qr_decal)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_transactions', to='wallet.posterminal'),
        ),
        migrations.CreateModel(
            name='POSPaymentPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('CLOSED', 'Ditutup')], default='ACTIVE', max_length=8)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_points', to='wallet.merchant')),
            ],
            options={
                'db_table': 'pos_payment_points',
            },
        ),
        migrations.CreateModel(
            name='POSQRDecal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('human_id', models.CharField(help_text='Short id printed on the sheet, e.g. KU-03', max_length=16)),
                ('nonce', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('SUPERSEDED', 'Digantikan'), ('REVOKED', 'Dicabut')], default='ACTIVE', max_length=12)),
                ('printed_at', models.DateTimeField()),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('grace_until', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, default='', max_length=255)),
                ('payment_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decals', to='wallet.pospaymentpoint')),
                ('printed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pos_qr_decals',
            },
        ),
        migrations.AddField(
            model_name='postransaction',
            name='qr_decal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wallet.posqrdecal'),
        ),
        migrations.AddIndex(
            model_name='pospaymentpoint',
            index=models.Index(fields=['foundation_id', 'merchant_id', 'status'], name='pos_payment_foundat_b9036d_idx'),
        ),
        migrations.AddIndex(
            model_name='posqrdecal',
            index=models.Index(fields=['foundation_id', 'payment_point_id', 'status'], name='pos_qr_deca_foundat_e18c58_idx'),
        ),
    ]
