# Generated by Django 5.1.15 on 2026-09-19 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0016_school_qr_self_amount_max"),
        ("wallet", "0012_static_qr_decals"),
    ]

    operations = [
        migrations.AddField(
            model_name="postransaction",
            name="qr_offline_nonce",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nonce from the offline-minted QR token; unique per terminal to reject replays (WAL-015)",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="POSTerminalSessionKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foundation_id",
                    models.BigIntegerField(
                        db_index=True,
                        help_text="ID of the governing Yayasan (foundation)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by", models.CharField(blank=True, max_length=64, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("key_id", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "secret_encrypted",
                    models.TextField(
                        help_text="Fernet-encrypted HMAC secret; never returned after issue time"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Aktif"), ("REVOKED", "Dicabut")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "grace_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Revoked key still verifies until this time",
                        null=True,
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_keys",
                        to="wallet.posterminal",
                    ),
                ),
            ],
            options={
                "db_table": "pos_terminal_session_keys",
            },
        ),
        migrations.AddField(
            model_name="postransaction",
            name="qr_offline_key",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this sale was authenticated by an offline-minted QR session token",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wallet.posterminalsessionkey",
            ),
        ),
        migrations.AddConstraint(
            model_name="postransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("qr_offline_nonce", ""), _negated=True),
                fields=("foundation_id", "terminal", "qr_offline_nonce"),
                name="unique_pos_transaction_qr_offline_nonce_per_terminal",
            ),
        ),
        migrations.AddIndex(
            model_name="posterminalsessionkey",
            index=models.Index(
                fields=["foundation_id", "terminal_id", "status"],
                name="pos_termina_foundat_664fa2_idx",
            ),
        ),
    ]
