# Generated by Django 5.1.15 on 2026-09-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_postransaction_qr_offline_nonce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='reject_reason',
            field=models.CharField(blank=True, default='', help_text='Spec-18 error code for a REJECTED self-entered charge', max_length=32),
        ),
    ]
