# Generated by Django 5.1.15 on 2026-09-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='operating_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='operating_start',
            field=models.TimeField(blank=True, help_text="Opening time in the school's timezone; with operating_end enables the out-of-hours decal alert (QRS-041)", null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='static_decal_daily_alert',
            field=models.PositiveIntegerField(default=300, help_text='A decal with more charges than this in a day raises an operations alert (QRS-041)'),
        ),
    ]
