# Generated by Django 5.1.15 on 2026-09-19 02:30

import apps.core.fields
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_decal_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantsettlement',
            name='adjustments_total',
            field=apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Upheld-dispute deductions absorbed by this run; net = gross - commission - adjustments_total', max_digits=18),
        ),
        migrations.CreateModel(
            name='MerchantSettlementAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('refund_amount', apps.core.fields.MoneyField(decimal_places=2, max_digits=18)),
                ('commission_recovered', apps.core.fields.MoneyField(decimal_places=2, max_digits=18)),
                ('deduction', apps.core.fields.MoneyField(decimal_places=2, max_digits=18)),
                ('occurred_at', models.DateTimeField()),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_adjustment', to='wallet.qrdispute')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_adjustments', to='wallet.merchant')),
                ('pos_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispute_adjustments', to='wallet.postransaction')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='wallet.merchantsettlement')),
            ],
            options={
                'db_table': 'merchant_settlement_adjustments',
                'indexes': [models.Index(fields=['foundation_id', 'merchant_id', 'settlement_id', 'occurred_at'], name='merchant_se_foundat_ba8b5e_idx')],
            },
        ),
    ]
