# Generated by Django 5.1.15 on 2026-09-19 03:34
# MySQL never created the conditional constraint from 0013 (models.W036), so the offline-token nonce was
# not unique there. Replace it with a plain unique constraint over a nullable column (TASK-071 pattern).

from django.db import migrations, models


def empty_to_null(apps, schema_editor):
    apps.get_model('wallet', 'POSTransaction')._base_manager.filter(qr_offline_nonce='').update(qr_offline_nonce=None)


def null_to_empty(apps, schema_editor):
    apps.get_model('wallet', 'POSTransaction')._base_manager.filter(qr_offline_nonce__isnull=True).update(qr_offline_nonce='')


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0017_user_pin'),
        ('wallet', '0016_settlement_adjustments'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='postransaction',
            name='unique_pos_transaction_qr_offline_nonce_per_terminal',
        ),
        migrations.AlterField(
            model_name='postransaction',
            name='qr_offline_nonce',
            field=models.CharField(blank=True, default=None, help_text='Nonce from the offline-minted QR token; unique per terminal to reject replays (WAL-015)', max_length=64, null=True),
        ),
        # '' was the old "no offline token" marker; NULL is the one a plain unique constraint ignores.
        migrations.RunPython(empty_to_null, null_to_empty),
        migrations.AddConstraint(
            model_name='postransaction',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'terminal', 'qr_offline_nonce'), name='unique_pos_transaction_qr_offline_nonce_per_terminal'),
        ),
    ]
