# Generated by Django 5.1.15 on 2026-09-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0017_user_pin'),
        ('wallet', '0016_settlement_adjustments'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='postransaction',
            name='unique_pos_transaction_qr_offline_nonce_per_terminal',
        ),
        migrations.AddField(
            model_name='postransaction',
            name='qr_offline_nonce_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True), models.Q(('qr_offline_nonce', ''), _negated=True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddConstraint(
            model_name='postransaction',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'terminal', 'qr_offline_nonce', 'qr_offline_nonce_uniq_marker'), name='unique_pos_transaction_qr_offline_nonce_per_terminal'),
        ),
    ]
