# Generated by Django 5.1.15 on 2026-09-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_pos_offline_nonce_mysql_unique'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='posterminal',
            index=models.Index(fields=['foundation_id', 'merchant', 'status'], name='idx_posterm_fnd_mer_st'),
        ),
    ]
