# Generated by Django 5.1.15 on 2026-09-19 04:55

import apps.core.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_tenant_foundation_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSTransactionArchive',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField()),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('merchant_id', models.BigIntegerField(db_column='merchant_id')),
                ('terminal_id', models.BigIntegerField(db_column='terminal_id', null=True)),
                ('student_id', models.BigIntegerField(db_column='student_id')),
                ('items', models.JSONField(default=list, help_text='List of {sku, name, qty, unit_price}')),
                ('subtotal', apps.core.fields.MoneyField(decimal_places=2, max_digits=18)),
                ('commission', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total', apps.core.fields.MoneyField(decimal_places=2, max_digits=18)),
                ('occurred_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('COMPLETED', 'Selesai'), ('REJECTED', 'Ditolak'), ('VOIDED', 'Dibatalkan')], default='COMPLETED', max_length=16)),
                ('offline_created', models.BooleanField(default=False)),
                ('client_transaction_id', models.CharField(max_length=128)),
                ('wallet_transaction_id', models.BigIntegerField(db_column='wallet_transaction_id', null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, default='', max_length=255)),
                ('entry_mode', models.CharField(choices=[('OPERATOR', 'Diinput petugas'), ('SELF_ENTERED', 'Diinput siswa')], default='OPERATOR', max_length=16)),
                ('qr_session_id', models.BigIntegerField(db_column='qr_session_id', null=True)),
                ('qr_decal_id', models.BigIntegerField(db_column='qr_decal_id', null=True)),
                ('confirmation_code', models.CharField(blank=True, default='', max_length=4)),
                ('qr_offline_key_id', models.BigIntegerField(db_column='qr_offline_key_id', null=True)),
                ('qr_offline_nonce', models.CharField(blank=True, default='', help_text='Nonce from the offline-minted QR token; unique per terminal to reject replays (WAL-015)', max_length=64)),
                ('reject_reason', models.CharField(blank=True, default='', help_text='Spec-18 error code for a REJECTED self-entered charge', max_length=32)),
            ],
            options={
                'db_table': 'pos_transactions_archive',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WalletTransactionArchive',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField()),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('wallet_id', models.BigIntegerField(db_column='wallet_id')),
                ('type', models.CharField(choices=[('TOPUP', 'Isi Ulang'), ('PURCHASE', 'Pembelian'), ('REFUND', 'Pengembalian'), ('ADJUSTMENT', 'Penyesuaian'), ('TRANSFER_OUT', 'Transfer Keluar')], max_length=16)),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, help_text='Signed delta: positive for TOPUP/REFUND, negative for PURCHASE/TRANSFER_OUT', max_digits=18)),
                ('balance_after', apps.core.fields.MoneyField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(blank=True, default='', max_length=128)),
                ('occurred_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('COMPLETED', 'Selesai'), ('REJECTED', 'Ditolak'), ('RECONCILE_REQUIRED', 'Perlu Rekonsiliasi')], default='COMPLETED', max_length=24)),
                ('idempotency_key', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'wallet_transactions_archive',
                'default_permissions': (),
            },
        ),
    ]
