# Generated by Django 5.1.15 on 2026-09-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_postransactionarchive_wallettransactionarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrdispute',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Terbuka'), ('UPHELD', 'Dikabulkan'), ('REJECTED', 'Ditolak'), ('VOIDED', 'Selesai (pembayaran dibatalkan)')], default='OPEN', max_length=16),
        ),
    ]
