# Generated by Django 5.2.17 on 2026-09-15 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0005_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('device_code', models.CharField(help_text='Unique hardware serial number or device identifier', max_length=64)),
                ('name', models.CharField(help_text='Friendly label, e.g. Gerbang Utama Masuk', max_length=128)),
                ('device_class', models.CharField(choices=[('GATE_READER', 'Gate Reader (Turnstile)'), ('FACE_TERMINAL', 'Face Terminal'), ('POS_TERMINAL', 'POS Terminal'), ('KIOSK', 'Kiosk'), ('HANDHELD', 'Handheld'), ('GATEWAY', 'Campus Gateway')], db_index=True, default='GATE_READER', max_length=32)),
                ('direction', models.CharField(choices=[('IN', 'Masuk (In)'), ('OUT', 'Keluar (Out)'), ('BIDIRECTIONAL', 'Dua Arah (Bidirectional)')], default='BIDIRECTIONAL', max_length=16)),
                ('location', models.CharField(blank=True, default='', help_text='Physical campus location', max_length=128)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('DEGRADED', 'Degraded'), ('RETIRED', 'Retired')], db_index=True, default='OFFLINE', max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Local IP address on campus LAN', null=True)),
                ('mac_address', models.CharField(blank=True, default='', max_length=32)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=64)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('today_event_count', models.PositiveIntegerField(default=0)),
                ('api_key_hash', models.CharField(blank=True, default='', max_length=128)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('school', models.ForeignKey(help_text='School where the device is deployed', on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='identity.school')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'devices',
                'abstract': False,
                'indexes': [models.Index(fields=['foundation_id', 'school', 'status'], name='idx_dev_fnd_sch_st'), models.Index(fields=['foundation_id', 'device_code'], name='idx_dev_fnd_code'), models.Index(fields=['foundation_id', 'device_class'], name='idx_dev_fnd_class')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('foundation_id', 'school', 'device_code'), name='unique_active_device_per_school')],
            },
        ),
    ]
