# Generated by Django 5.1.15 on 2026-09-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
        ('identity', '0005_staff'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='device',
            name='unique_active_device_per_school',
        ),
        migrations.AddField(
            model_name='device',
            name='active_uniq_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'school', 'device_code', 'active_uniq_marker'), name='unique_active_device_per_school'),
        ),
    ]
