# Generated by Django 5.1.15 on 2026-09-18 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_remove_device_unique_active_device_per_school_and_more'),
        ('identity', '0012_microsofttenantconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEventStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event_uuid', models.UUIDField(db_index=True, help_text='Client-generated idempotent UUID from edge gateway (HW-005)', unique=True)),
                ('payload', models.JSONField(help_text='Raw event fields as uploaded: occurred_at, raw_uid, direction, method, etc.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('error_text', models.CharField(blank=True, default='', max_length=500)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staged_events', to='hardware.device')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_event_staging_rows', to='identity.school')),
            ],
            options={
                'verbose_name': 'Device Event Staging Row',
                'verbose_name_plural': 'Device Event Staging Rows',
                'db_table': 'device_event_staging',
                'abstract': False,
                'indexes': [models.Index(fields=['foundation_id', 'status', 'created_at'], name='idx_devevtstg_fnd_st_crt'), models.Index(fields=['foundation_id', 'school', 'status'], name='idx_devevtstg_fnd_sch_st')],
            },
        ),
    ]
