# Generated by Django 5.1.15 on 2026-09-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_deviceeventstaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('subject_type', models.CharField(choices=[('STUDENT', 'Siswa'), ('STAFF', 'Staf')], db_index=True, max_length=16)),
                ('subject_id', models.BigIntegerField(help_text='Student.id or Staff.id')),
                ('device_class', models.CharField(choices=[('GATE_READER', 'Gate Reader (Turnstile)'), ('FACE_TERMINAL', 'Face Terminal'), ('POS_TERMINAL', 'POS Terminal'), ('KIOSK', 'Kiosk'), ('HANDHELD', 'Handheld'), ('GATEWAY', 'Campus Gateway')], default='FACE_TERMINAL', help_text='Enrollment device class — always FACE_TERMINAL today; kept general per spec/12 §2', max_length=32)),
                ('consent_id', models.BigIntegerField(help_text='apps.compliance.ConsentRecord.id this enrollment relies on (CMP-009: no bundling, no template without a purpose-matched consent)')),
                ('template_ciphertext', models.TextField(blank=True, default='', help_text='Fernet-encrypted template payload; blanked on withdrawal/purge')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('WITHDRAWN', 'Ditarik (Consent Withdrawn)'), ('PURGED', 'Dihapus (Purged)')], db_index=True, default='ACTIVE', max_length=16)),
                ('enrolled_at', models.DateTimeField()),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Biometric Template',
                'verbose_name_plural': 'Biometric Templates',
                'db_table': 'biometric_templates',
                'abstract': False,
                'indexes': [models.Index(fields=['foundation_id', 'subject_type', 'subject_id', 'status'], name='idx_biotpl_fnd_subj_st'), models.Index(fields=['foundation_id', 'status'], name='idx_biotpl_fnd_st')],
            },
        ),
    ]
