# Generated by Django 5.1.15 on 2026-09-19 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_biometrictemplate'),
        ('identity', '0020_user_activity_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUptimeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField(help_text='School-local calendar date')),
                ('samples', models.PositiveIntegerField(default=0)),
                ('up_samples', models.PositiveIntegerField(default=0)),
                ('active_uniq_marker', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField())),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_uptime_days', to='identity.school')),
            ],
            options={
                'db_table': 'device_uptime_days',
                'abstract': False,
                'indexes': [models.Index(fields=['foundation_id', 'school', 'date'], name='idx_devup_fnd_sch_date')],
                'constraints': [models.UniqueConstraint(fields=('foundation_id', 'school', 'date', 'active_uniq_marker'), name='unique_device_uptime_day_per_school_date')],
            },
        ),
    ]
