# Generated by Django 5.2.17 on 2026-09-15 00:47

import apps.core.fields
import datetime
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0005_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recipient_phone', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=128)),
                ('category', models.CharField(choices=[('ARRIVAL', 'Kedatangan (Arrival)'), ('DEPARTURE', 'Kepulangan (Departure)'), ('EMERGENCY', 'Darurat (Emergency)'), ('PAYMENT_DUE', 'Tagihan Pembayaran (Payment Due)'), ('PAYMENT_RECEIVED', 'Pembayaran Diterima (Payment Received)'), ('GRADE_PUBLISHED', 'Nilai Diumumkan (Grade Published)'), ('REPORT_CARD', 'Buku Rapor (Report Card)'), ('HOMEWORK', 'Tugas Sekolah (Homework)'), ('BEHAVIOUR_MAJOR', 'Pelanggaran Berat (Major Behaviour)'), ('BEHAVIOUR_MINOR', 'Catatan Ringan (Minor Behaviour)'), ('CANTEEN', 'Transaksi Kantin (Canteen)'), ('ANNOUNCEMENT', 'Pengumuman Sekolah (Announcement)')], max_length=64)),
                ('template_key', models.CharField(db_index=True, max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('NORMAL', 'Normal'), ('LOW', 'Low')], db_index=True, default='NORMAL', max_length=32)),
                ('scheduled_for', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DISPATCHED', 'Dispatched'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=32)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, help_text='Idempotency dedupe key (NTF-003)', max_length=255, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_intents', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_intents', to='identity.school')),
            ],
            options={
                'db_table': 'notification_intents',
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('PUSH', 'Push Notification'), ('SMS', 'SMS'), ('EMAIL', 'Email'), ('IN_APP', 'In-App')], max_length=32)),
                ('provider', models.CharField(default='mock', max_length=64)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('recipient_target', models.CharField(blank=True, default='', max_length=128)),
                ('rendered_subject', models.CharField(blank=True, default='', max_length=255)),
                ('rendered_body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=32)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('cost', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Per-channel provider cost per NTF-011', max_digits=18)),
                ('cost_currency', models.CharField(default='IDR', max_length=3)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='notifications.notificationintent')),
            ],
            options={
                'db_table': 'notification_deliveries',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('category', models.CharField(choices=[('ARRIVAL', 'Kedatangan (Arrival)'), ('DEPARTURE', 'Kepulangan (Departure)'), ('EMERGENCY', 'Darurat (Emergency)'), ('PAYMENT_DUE', 'Tagihan Pembayaran (Payment Due)'), ('PAYMENT_RECEIVED', 'Pembayaran Diterima (Payment Received)'), ('GRADE_PUBLISHED', 'Nilai Diumumkan (Grade Published)'), ('REPORT_CARD', 'Buku Rapor (Report Card)'), ('HOMEWORK', 'Tugas Sekolah (Homework)'), ('BEHAVIOUR_MAJOR', 'Pelanggaran Berat (Major Behaviour)'), ('BEHAVIOUR_MINOR', 'Catatan Ringan (Minor Behaviour)'), ('CANTEEN', 'Transaksi Kantin (Canteen)'), ('ANNOUNCEMENT', 'Pengumuman Sekolah (Announcement)')], max_length=64)),
                ('channels', models.JSONField(default=list, help_text='Ordered list of preferred channels')),
                ('quiet_hours_start', models.TimeField(default=datetime.time(21, 0), help_text='Default 21:00 local')),
                ('quiet_hours_end', models.TimeField(default=datetime.time(6, 0), help_text='Default 06:00 local')),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('key', models.CharField(db_index=True, help_text='e.g. attendance.arrival', max_length=128)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('PUSH', 'Push Notification'), ('SMS', 'SMS'), ('EMAIL', 'Email'), ('IN_APP', 'In-App')], default='WHATSAPP', max_length=32)),
                ('locale', models.CharField(default='id-ID', help_text='Default id-ID per NTF-008', max_length=10)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(help_text='Message template with {variable} placeholders')),
                ('variables', models.JSONField(default=list, help_text='Declared variable keys')),
                ('version', models.PositiveIntegerField(default=1)),
                ('approval_status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='APPROVED', help_text='Approval tracking for WhatsApp templates (NTF-005)', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='identity.school')),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.AddIndex(
            model_name='notificationintent',
            index=models.Index(fields=['foundation_id', 'status', 'scheduled_for'], name='notificatio_foundat_d49232_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationintent',
            index=models.Index(fields=['foundation_id', 'recipient_phone'], name='notificatio_foundat_0d3eab_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationintent',
            index=models.Index(fields=['foundation_id', 'dedupe_key'], name='notificatio_foundat_c34ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['foundation_id', 'status', 'created_at'], name='notificatio_foundat_5484a0_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['provider', 'provider_message_id'], name='notificatio_provide_216f38_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('foundation_id', 'user', 'category'), name='unique_user_notification_preference'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['foundation_id', 'key', 'channel', 'locale'], name='notificatio_foundat_c909af_idx'),
        ),
    ]
