# Generated by Django 5.2.17 on 2026-09-16 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificationintent_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationintent',
            name='category',
            field=models.CharField(choices=[('ARRIVAL', 'Kedatangan (Arrival)'), ('DEPARTURE', 'Kepulangan (Departure)'), ('EMERGENCY', 'Darurat (Emergency)'), ('PAYMENT_DUE', 'Tagihan Pembayaran (Payment Due)'), ('PAYMENT_RECEIVED', 'Pembayaran Diterima (Payment Received)'), ('GRADE_PUBLISHED', 'Nilai Diumumkan (Grade Published)'), ('REPORT_CARD', 'Buku Rapor (Report Card)'), ('HOMEWORK', 'Tugas Sekolah (Homework)'), ('BEHAVIOUR_MAJOR', 'Pelanggaran Berat (Major Behaviour)'), ('BEHAVIOUR_MINOR', 'Catatan Ringan (Minor Behaviour)'), ('CANTEEN', 'Transaksi Kantin (Canteen)'), ('ANNOUNCEMENT', 'Pengumuman Sekolah (Announcement)'), ('WALLET_RECONCILIATION', 'Rekonsiliasi Dompet (Wallet Reconciliation)'), ('SUBSTITUTE_ASSIGNED', 'Penugasan Guru Pengganti (Substitute Assigned)'), ('SUBSTITUTE_DECLINED', 'Penolakan Guru Pengganti (Substitute Declined)')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='category',
            field=models.CharField(choices=[('ARRIVAL', 'Kedatangan (Arrival)'), ('DEPARTURE', 'Kepulangan (Departure)'), ('EMERGENCY', 'Darurat (Emergency)'), ('PAYMENT_DUE', 'Tagihan Pembayaran (Payment Due)'), ('PAYMENT_RECEIVED', 'Pembayaran Diterima (Payment Received)'), ('GRADE_PUBLISHED', 'Nilai Diumumkan (Grade Published)'), ('REPORT_CARD', 'Buku Rapor (Report Card)'), ('HOMEWORK', 'Tugas Sekolah (Homework)'), ('BEHAVIOUR_MAJOR', 'Pelanggaran Berat (Major Behaviour)'), ('BEHAVIOUR_MINOR', 'Catatan Ringan (Minor Behaviour)'), ('CANTEEN', 'Transaksi Kantin (Canteen)'), ('ANNOUNCEMENT', 'Pengumuman Sekolah (Announcement)'), ('WALLET_RECONCILIATION', 'Rekonsiliasi Dompet (Wallet Reconciliation)'), ('SUBSTITUTE_ASSIGNED', 'Penugasan Guru Pengganti (Substitute Assigned)'), ('SUBSTITUTE_DECLINED', 'Penolakan Guru Pengganti (Substitute Declined)')], max_length=64),
        ),
        migrations.CreateModel(
            name='DevicePushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_id', models.BigIntegerField(db_index=True, help_text='ID of the governing Yayasan (foundation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('token', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], default='ANDROID', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('active_uniq_marker', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('deleted_at__isnull', True)), then=models.Value(0)), default=models.Value(None), output_field=models.IntegerField()), null=True, output_field=models.IntegerField())),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_push_tokens',
                'indexes': [models.Index(fields=['foundation_id', 'user_id', 'is_active'], name='device_push_foundat_c02f22_idx')],
                'constraints': [models.UniqueConstraint(fields=('foundation_id', 'user', 'token', 'active_uniq_marker'), name='unique_user_device_push_token')],
            },
        ),
    ]
