# Generated by Django 5.1.15 on 2026-09-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notificationintent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationintent',
            name='category',
            field=models.CharField(choices=[('ARRIVAL', 'Kedatangan (Arrival)'), ('DEPARTURE', 'Kepulangan (Departure)'), ('EMERGENCY', 'Darurat (Emergency)'), ('PAYMENT_DUE', 'Tagihan Pembayaran (Payment Due)'), ('PAYMENT_RECEIVED', 'Pembayaran Diterima (Payment Received)'), ('GRADE_PUBLISHED', 'Nilai Diumumkan (Grade Published)'), ('REPORT_CARD', 'Buku Rapor (Report Card)'), ('HOMEWORK', 'Tugas Sekolah (Homework)'), ('BEHAVIOUR_MAJOR', 'Pelanggaran Berat (Major Behaviour)'), ('BEHAVIOUR_MINOR', 'Catatan Ringan (Minor Behaviour)'), ('CANTEEN', 'Transaksi Kantin (Canteen)'), ('ANNOUNCEMENT', 'Pengumuman Sekolah (Announcement)'), ('WALLET_RECONCILIATION', 'Rekonsiliasi Dompet (Wallet Reconciliation)'), ('SUBSTITUTE_ASSIGNED', 'Penugasan Guru Pengganti (Substitute Assigned)'), ('SUBSTITUTE_DECLINED', 'Penolakan Guru Pengganti (Substitute Declined)'), ('EXPORT_READY', 'Ekspor Laporan Siap (Export Ready)'), ('ABSENCE', 'Ketidakhadiran (Absence)'), ('DEVICE_OFFLINE', 'Perangkat Offline (Device Offline)'), ('DAILY_DIGEST', 'Ringkasan Aktivitas Harian (Daily Digest)'), ('LIBRARY_LOAN_DUE', 'Peminjaman Perpustakaan Jatuh Tempo (Library Loan Due)')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='category',
            field=models.CharField(choices=[('ARRIVAL', 'Kedatangan (Arrival)'), ('DEPARTURE', 'Kepulangan (Departure)'), ('EMERGENCY', 'Darurat (Emergency)'), ('PAYMENT_DUE', 'Tagihan Pembayaran (Payment Due)'), ('PAYMENT_RECEIVED', 'Pembayaran Diterima (Payment Received)'), ('GRADE_PUBLISHED', 'Nilai Diumumkan (Grade Published)'), ('REPORT_CARD', 'Buku Rapor (Report Card)'), ('HOMEWORK', 'Tugas Sekolah (Homework)'), ('BEHAVIOUR_MAJOR', 'Pelanggaran Berat (Major Behaviour)'), ('BEHAVIOUR_MINOR', 'Catatan Ringan (Minor Behaviour)'), ('CANTEEN', 'Transaksi Kantin (Canteen)'), ('ANNOUNCEMENT', 'Pengumuman Sekolah (Announcement)'), ('WALLET_RECONCILIATION', 'Rekonsiliasi Dompet (Wallet Reconciliation)'), ('SUBSTITUTE_ASSIGNED', 'Penugasan Guru Pengganti (Substitute Assigned)'), ('SUBSTITUTE_DECLINED', 'Penolakan Guru Pengganti (Substitute Declined)'), ('EXPORT_READY', 'Ekspor Laporan Siap (Export Ready)'), ('ABSENCE', 'Ketidakhadiran (Absence)'), ('DEVICE_OFFLINE', 'Perangkat Offline (Device Offline)'), ('DAILY_DIGEST', 'Ringkasan Aktivitas Harian (Daily Digest)'), ('LIBRARY_LOAN_DUE', 'Peminjaman Perpustakaan Jatuh Tempo (Library Loan Due)')], max_length=64),
        ),
    ]
